coreshop/CoreShop

.gitignore
config/startup.php

added the ability to add a shop theme to website structure.
https://github.com/dpfaffenbauer/pimcore-coreshop/issues/28

https://github.com/dpfaffenbauer/pimcore-coreshop/issues/28

---

static/js/coreshop/countries/country.js

fix country.js typecasting for active state.

https://github.com/dpfaffenbauer/pimcore-coreshop/issues/30 [#30]

---

install/sql/v-0.1.sql
lib/CoreShop/Plugin/Install.php

- check if customview already exists
- fix camelcase in db insertion

Pimcore 4.0

---

composer.json

geoip already served by pimcore.

remove geoip from composer

---

static/texts/de.csv

Fix system settings translation typo

---

tests/bootstrap.php
tests/lib/CoreShop/Test/Base.php

@dpfaffenbauer - per our conversation

Small cleanup of the default Pimcore unit testing template

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig

[CoreBundle, IndexBundle] Tax filter

---

composer.json
src/CoreShop/Bundle/CoreBundle/Application/RegisterBundleHelper.php
src/CoreShop/Bundle/FrontendBundle/Controller/MailController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/layout.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/mail.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/order-confirmation.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/_footer.html.twig
src/CoreShop/Bundle/FrontendBundle/composer.json
src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/footer.html.twig

[FrontendBundle] Emailizr

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/AddressCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/PaymentCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/ShippingCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php

#216: Better handling of form-errors in checkout-steps

---

docs/03_Development/06_Order/09_AdditionalData.md
src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail.js
src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
src/CoreShop/Component/Core/Order/OrderMailProcessor.php
src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
src/CoreShop/Component/Order/Notes.php
src/CoreShop/Component/Resource/Pimcore/DataObjectNoteService.php

[CoreBundle, Order] Mail correspondence

---

src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
src/CoreShop/Component/Order/Transformer/AbstractCartItemToSaleItemTransformer.php
src/CoreShop/Component/Order/Transformer/AbstractCartToSaleTransformer.php
src/CoreShop/Component/Order/Transformer/CartToOrderTransformer.php
src/CoreShop/Component/Order/Transformer/OrderItemToInvoiceItemTransformer.php
src/CoreShop/Component/Order/Transformer/OrderItemToShipmentItemTransformer.php
src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php
src/CoreShop/Component/Pimcore/VersionHelper.php

Disable Versions for various CoreShop Objects

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php

Allow better category and product getter overrides.

SEO Optimization

---

src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php

Revert "[FrontendBundle] make reset password url absolute"

---

src/CoreShop/Bundle/CoreBundle/EventListener/Order/InventoryLockingProductsListener.php
src/CoreShop/Component/Core/Inventory/Operator/OrderInventoryOperator.php
src/CoreShop/Component/Core/Inventory/Operator/OrderInventoryOperatorInterface.php

fixes cancel release see #265.

Inventory locking

---

src/CoreShop/Bundle/CoreBundle/Form/Type/CustomerRegistrationType.php
src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Security/_login-form.html.twig

When registration is called from checkout process, it should redirect back when done.

[FrontendBundle] Registration can redirect back to checkout

---

src/CoreShop/Bundle/AddressBundle/Form/Type/AddressType.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/address.html.twig

When new address is added from checkout process, it should redirect back when done.

[FrontendBundle] Customer Address can redirect back to checkout

---

src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php

Fixes search controller returning all active products regardless of the search because active is set in an "OR" condition.

Fixed search condition filtering only products set as active

---

controllers/CheckoutController.php
lib/CoreShop/Model/Rules/AbstractRule.php

Fix redirect after click checkout url on top menu

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/layout.html.twig

zurb_ink has been replaced by emailizr

Fix style loading

---

docs/03_Development/01_Extending_Guide/04_Extending_Rule_Actions.md

Did not work as described, some paths changed
docs only

Fix docs example

---

src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php

Disallow product rendering if a store is selected which is not allowed in the product.

Proposal: Product display restriction by store

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderInvoiceController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderShipmentController.php
src/CoreShop/Component/Order/Processable/ProcessableInterface.php
src/CoreShop/Component/Order/Processable/ProcessableOrderItems.php

[OrderBundle] allow a more flexible way of defining if order-documents are allowed to be created or not

---

src/CoreShop/Bundle/IndexBundle/Condition/MysqlRenderer.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing/Dao.php
src/CoreShop/Component/Index/Condition/AbstractRenderer.php
src/CoreShop/Component/Index/Condition/RendererInterface.php
src/CoreShop/Component/Index/Worker/WorkerInterface.php

[Index] add prefix to mysql query

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing/Dao.php

Add prefix to mysql worker listing

Add prefix to mysql worker listing

---

features/index/boolean_column.feature
features/index/create_index.feature
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
src/CoreShop/Behat/Context/Transform/PimcoreClassContext.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php

[IndexBundle] fix issue with storing boolean false values

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/IndexBundle/Condition/MysqlRenderer.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Condition/CompareCondition.php
src/CoreShop/Component/Index/Condition/ConcatCondition.php
src/CoreShop/Component/Index/Condition/Condition.php
src/CoreShop/Component/Index/Condition/ConditionInterface.php
src/CoreShop/Component/Index/Condition/GreaterThanCondition.php
src/CoreShop/Component/Index/Condition/GreaterThanEqualCondition.php
src/CoreShop/Component/Index/Condition/InCondition.php
src/CoreShop/Component/Index/Condition/IsCondition.php
src/CoreShop/Component/Index/Condition/LikeCondition.php
src/CoreShop/Component/Index/Condition/LowerThanCondition.php
src/CoreShop/Component/Index/Condition/LowerThanEqualCondition.php
src/CoreShop/Component/Index/Condition/MatchCondition.php
src/CoreShop/Component/Index/Condition/NotMatchCondition.php
src/CoreShop/Component/Index/Condition/RangeCondition.php
src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
src/CoreShop/Component/Index/Filter/SelectFilterConditionProcessor.php

[Index] refactor condition classes and create concrete classes for each condition type

---

src/CoreShop/Bundle/CoreBundle/Application/Version.php

Coreshop has wrong version in Pimcore Admin

Set proper version

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStorePriceRepository.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20180527091927.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStorePrice.orm.yml
src/CoreShop/Component/Core/Model/ProductStorePrice.php
src/CoreShop/Component/Core/Model/ProductStorePriceInterface.php
src/CoreShop/Component/Core/Repository/ProductStorePriceRepositoryInterface.php

| Fixed tickets | #426
This allows to have multiple types of StorePrice in an data-object class.

[StorePrice] allow to have multiple store prices in a object

---

features/cli/install_demo_data_command.feature
src/CoreShop/Behat/Context/Cli/InstallerContext.php
src/CoreShop/Behat/Resources/config/services/contexts.yml
src/CoreShop/Behat/Resources/config/services/contexts/cli.yml
src/CoreShop/Behat/Resources/config/suites.yml
src/CoreShop/Behat/Resources/config/suites/domain/cli.yml

[Behat] add install fixtures tests

---

features/index/create_index_with_products.feature
features/index/index_unpublished.feature
features/index/index_unpublished_product.feature
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
src/CoreShop/Behat/Context/Setup/ProductContext.php
src/CoreShop/Behat/Model/Index/TestEnableIndex.php
src/CoreShop/Component/Core/Model/Product.php

[Index] fixes for indexable in product class + behat tests for enabled

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20180615074917.php
src/CoreShop/Bundle/CurrencyBundle/Form/Type/ExchangeRateType.php
src/CoreShop/Bundle/CurrencyBundle/Resources/config/doctrine/model/ExchangeRate.orm.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/exchangeRate/panel.js

[ExchangeRate] increase decimal scale to 10

---

src/CoreShop/Bundle/CoreBundle/Application/Version.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/SerializedData.php
src/CoreShop/Component/Customer/Model/Customer.php
src/CoreShop/Component/Customer/Model/CustomerInterface.php
src/CoreShop/Component/Order/Model/Order.php
src/CoreShop/Component/Order/Model/OrderInterface.php
src/CoreShop/Component/Order/Model/Quote.php
src/CoreShop/Component/Order/Model/QuoteInterface.php
src/CoreShop/Component/Order/Model/SaleInterface.php

[Beta.2] beta.2 release

---

src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/conditions/timespan.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/conditions/timespan.js

[Timespan Conditions] use todays date. fixes

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/state/changeState.js
src/CoreShop/Bundle/WorkflowBundle/EventListener/WorkflowListener.php

[OrderBundle, WorkflowBundle] #425: implement before dispatcher

---

src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/CustomerBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice/render.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment/render.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource.js

| Fixed tickets | pimcore/pimcore#2992

[All] fix CSRF Pimcore Issue

---

CHANGELOG.md
src/CoreShop/Component/Customer/Model/Customer.php
src/CoreShop/Component/Customer/Model/CustomerInterface.php

[Customer] rename constants to allow integration with Members Bundle

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php

| Fixed tickets | #502
This PR allows custom redirects after a product has been added to cart / wishlist.

Implement custom redirect for item adding

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Component/Index/Interpreter/RelationalValue.php
src/CoreShop/Component/Index/Interpreter/RelationalValueInterface.php

[Index] add RelationalValueInterface to better determine return type of relational interpreter

---

src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/panel.js

[OrderBundle] fix order detail glitch

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/index.html.twig

Should probably use form anyway but this'll make it look a little bit better in the meantime.

Capitalize sort option

---

src/CoreShop/Bundle/ConfigurationBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/RuleBundle/Resources/config/app/config.yml
src/CoreShop/Bundle/RuleBundle/Resources/config/app/coreshop_rule.yml
src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/config.yml

[JMSSerializer config] fix wrong configurations

---

src/CoreShop/Bundle/ProductBundle/EventListener/ProductDeleteListener.php
src/CoreShop/Bundle/ProductBundle/Resources/config/services.yml

[ProductBundle] delete product specific price rules on product deletion

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php

[CoreBundle] apply almost same params for every customer notification event

---

src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php

by removing description (=to generic) and fix store search, otherwise all products of the store would be found

[FrontendBundle] fix search

---

features/product/specific_price_rules/nested_condition.feature
src/CoreShop/Behat/Context/Setup/ProductSpecificPriceRuleContext.php
src/CoreShop/Component/Rule/Condition/NestedConditionChecker.php

[RuleBundle] fix for nested condition and checker including a behat test

---

features/pimcore/test_static_files.feature
src/CoreShop/Behat/Context/Domain/PimcoreContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/suites/domain/pimcore.yml
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Extension/AbstractPimcoreExtension.php

[Behat] add tests for static resources

---

src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
src/CoreShop/Component/Order/Modifier/VoucherModifier.php
src/CoreShop/Component/Order/Modifier/VoucherModifierInterface.php

store voucher usages

---

src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php

[IndexBundle] make index-command more performant

---

src/CoreShop/Bundle/OrderBundle/Renderer/AssetOrderDocumentPdfRenderer.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/pdf.yml

[OrderBundle] inject env as parameter and not use pimcores static function

---

src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php

Improve Object Manager by making a difference between new and updated objects and only store them once instead of multiple times.

[ResourceBundle] improve Pimcore ObjectManager

---

src/CoreShop/Bundle/CoreBundle/Controller/CoreSaleCreationTrait.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php

[OrderBundle, CoreBundle] fix Order creation for inherited values

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20180719151524.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
tests/lib/CoreShop/Test/PHPUnit/Suites/Product/SpecificPrice.php

make Product Specific Price Rules extension and Store Price Extension lazy loading for better performance

[CoreBundle, ProductBundle] Lazy Loading Core Extensions

---

src/CoreShop/Bundle/CoreBundle/Application/Version.php

https://github.com/coreshop/CoreShop/milestone/5?closed=1

[Beta.3] prepare beta.3 release

---

.travis.yml

[Travis] add tests for Pimcore 5.3.0

---

tests/behat-bootstrap.php

[Tests] fix bootstrap

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/dashboard/portlets/order_cart.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/dashboard/portlets/sales.js

https://github.com/pimcore/pimcore/pull/3106

[CoreBundle] make portlets compatible with Pimcore 5.4.0

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

by loading all prices only once on persist

[CoreBundle] further improve persisting time of StorePrices 

---

src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php

[OrderBundle] fix OrderState grid operator

---

src/CoreShop/Component/Core/Translation/TranslatableEntityPimcoreLocaleAssigner.php
src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php

Pimcore changed the Service Name and therefore we need to change it as well.

[Core, Locale] fix usage of LocaleService

---

src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php

Fix orderState check in payum extension

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/summary.html.twig

[Inventory] check tracked inventory for all items including those in cart

---

src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php

| Fixed tickets | #344
install the docs in a site if available, otherwise it installs them into root. #344

[ResourceBundle] improve document installer

---

src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
src/CoreShop/Bundle/CoreBundle/Command/InstallResourcesCommand.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml

The command does more than just installing classes, it also installs translations, documents, etc.

[CoreBundle] rename InstallClasses Command to InstallResources

---

src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/ExpressionLanguageServicePass.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
src/CoreShop/Component/Index/Interpreter/ExpressionInterpreter.php
src/CoreShop/Component/Pimcore/ExpressionLanguage/ExpressionLanguage.php
src/CoreShop/Component/Pimcore/ExpressionLanguage/PHPFunctionsProvider.php
src/CoreShop/Component/Pimcore/ExpressionLanguage/PimcoreLanguageProvider.php
src/CoreShop/Component/Pimcore/Placeholder/Expression.php

This PR makes it possible to easier extend the Expression Language Providers by defining a tag on a service.

[Expression] refactor expression engine to be extendable via services

---

src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php

[ResourceBundle] fix getClassIds for StackRepository

---

src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
src/CoreShop/Component/Pimcore/DataObject/ClassDefinitionFieldReNamer.php
src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
src/CoreShop/Component/Pimcore/DataObject/ClassUpdateRenameInterface.php
src/CoreShop/Component/Pimcore/DataObject/DefinitionFieldReNamerInterface.php

[Pimcore] implement field renamer for better migrations

---

src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php

fixup for commit https://github.com/coreshop/CoreShop/commit/1e31abb056488a6202cb06c626d5ad839b9f66de#diff-c0477c69d776b182bb9dd69b7717407c
| Fixed tickets | –

fix wishlist findTemplate() parameter

---

src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php

| Fixed tickets | #620
Check if given Locale from Pimcore is a valid Pimcore Locale

[Locale] only return a valid locale

---

src/CoreShop/Component/Pimcore/Twig/Extension/ImageThumbnailExtension.php
src/CoreShop/Component/Pimcore/Twig/Extension/ObjectHelperExtensions.php

[Pimcore] Introduce a new Image Thumbnail Twig Extension

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/EmbeddedClass.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php

https://github.com/pimcore/pimcore/issues/3313

[CoreExtensions] stay compatible with Pimcore 5.5 

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

add StorePrice CSV import/export feature; resolve #637

---

CONTRIBUTING.md

BTW, is creating an issue **not necessary at all** for bug fixes, or is just writing the ”approach to solving“ a problem not necessary for bug fixes? Somewhat ambiguous phrasing.

fix typo in contributing readme

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml

[ResourceBundle] properly configure jms-serializer

---

src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml

compare https://github.com/coreshop/CoreShop/commit/41581c08c9#r30803205
| Fixed tickets | –

[fix] productDetailFancy thumbnail: contain -> scaleByWidth

---

src/CoreShop/Bundle/CurrencyBundle/Form/Type/CurrencyType.php
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/currency/item.js

[Currency] fix save currency

---

etc/_scripts/phpunit
phpunit.xml.dist
src/CoreShop/Component/Pimcore/BatchProcessing/BatchListing.php
tests/lib/CoreShop/Test/PHPUnit/Component/Pimcore/BatchListingTest.php
tests/lib/CoreShop/Test/PHPUnit/Component/Pimcore/Suite.php

[Pimcore] introduce batch list helper

---

composer.json
src/CoreShop/Bundle/CoreBundle/composer.json

[Composer] use rivenx/countries instead of rivenx/country

---

src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SerializedData.php
src/CoreShop/Component/Core/Model/Carrier.php
src/CoreShop/Component/Core/Model/Country.php
src/CoreShop/Component/Core/Model/PaymentProvider.php

| Fixed tickets | #685
This PR fixes the preview generator of versions and QuickSearch.

[PimcoreBundle, Core] fix version / quickSearch preview

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
src/CoreShop/Bundle/CoreBundle/Security/ObjectUserProvider.php

| Fixed tickets | #662, #686 
This PR will fix login issues described in the issues above.

[CoreBundle] check guest state in ObjectUserProvider

---

features/index_condition/mysql/compare_condition.feature
features/index_condition/mysql/concat_condition.feature
features/index_condition/mysql/in_condition.feature
features/index_condition/mysql/like_condition.feature
features/index_condition/mysql/null_condition.feature
features/index_condition/mysql/range_condition.feature
src/CoreShop/Behat/Context/Domain/IndexConditionContext.php
src/CoreShop/Behat/Context/Setup/IndexConditionContext.php
src/CoreShop/Behat/Context/Transform/IndexConditionContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Behat/Resources/config/services/contexts/transform.yml
src/CoreShop/Behat/Resources/config/suites.yml
src/CoreShop/Behat/Resources/config/suites/domain/index_condition.yml
src/CoreShop/Bundle/IndexBundle/Condition/MysqlRenderer.php
src/CoreShop/Component/Index/Condition/IsNotNullCondition.php
src/CoreShop/Component/Index/Condition/IsNullCondition.php
src/CoreShop/Component/Index/Condition/NotInCondition.php
src/CoreShop/Component/Index/Condition/NotLikeCondition.php

[IndexBundle, Behat] add negative condition classes and behat tests

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Mail/order-confirmation.html.twig
src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
src/CoreShop/Bundle/PaymentBundle/Form/Type/PaymentProviderChoiceType.php

[PaymentBundle] fix Attempted to call an undefined method named "getName"

---

features/cart/rules/amount_condition.feature
features/cart/rules/category_condition.feature
features/cart/rules/country_condition.feature
features/cart/rules/currency_condition.feature
features/cart/rules/customer_condition.feature
features/cart/rules/customer_group_condition.feature
features/cart/rules/discount_amount_action.feature
features/cart/rules/discount_percent_action.feature
features/cart/rules/product_condition.feature
features/cart/rules/store_condition.feature
features/cart/rules/timespan_condition.feature
features/cart/rules/zone_condition.feature
src/CoreShop/Behat/Context/Domain/CartContext.php
src/CoreShop/Behat/Context/Domain/CartPriceRuleContext.php
src/CoreShop/Behat/Context/Setup/CartContext.php
src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
src/CoreShop/Behat/Context/Setup/StoreContext.php
src/CoreShop/Behat/Context/Transform/CartPriceRuleContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Behat/Resources/config/services/contexts/transform.yml
src/CoreShop/Behat/Resources/config/suites/domain/cart.yml

[Behat] implement behat for cart-rules

---

CHANGELOG.md
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/flash_messages.html.twig

[FrontendBundle] translate flash messages in the controller to make them more consistant

---

features/cart/rules/free_shipping_action.feature
src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
src/CoreShop/Behat/Resources/config/suites/domain/cart.yml

[Behat] add cart-price-rule free-shipping action tests

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php

[OrderBundle] fix getTitle for carrier

---

src/CoreShop/Bundle/IndexBundle/EventListener/IndexObjectListener.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php

[IndexBundle] move inheritanceHelper to IndexObjectListener

---

src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
src/CoreShop/Component/Core/Order/Transformer/CartItemToSaleItemTransformer.php

show category key if no name is available in category report

---

features/cart/delete_cart_item_on_unpublish.feature
src/CoreShop/Behat/Context/Domain/CartContext.php
src/CoreShop/Behat/Context/Hook/PimcoreDaoContext.php
src/CoreShop/Behat/Context/Transform/ProductContext.php
src/CoreShop/Bundle/CoreBundle/EventListener/ProductAvailabilityEventListener.php

[Behat, CoreBundle] fix ProductAvailabilityListener and test cases

---

src/CoreShop/Bundle/IndexBundle/Controller/IndexController.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

| Fixed tickets | #703 
for MySQL Index doctrine takes care about creating the mapping (creating columns and transforming values)

[IndexBundle] allow to define custom mapping types

---

features/cart/delete_cart_item_on_unpublish.feature
src/CoreShop/Bundle/CoreBundle/EventListener/ProductAvailabilityEventListener.php

[CoreBundle] fix availability check

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

[CoreBundle, MoneyBundle] fix for #701

---

src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/list.js

This PR improves the sales list js structure and also introduces three new events:
- `sales.list.enhancing.grid`
- `sales.list.enhancing.toolbar`
- `sales.list.enhancing.grid-paginator`

[OrderBundle] improve sale list view, implement some events

---

src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php

Utf8 safely path for folders

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php

Fix Filter Query

---

src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Store.orm.yml

[CoreBundle] remove cascading of store deletetions for countries

---

src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php
src/CoreShop/Component/Core/Tracking/Extractor/ProductExtractor.php

check if variable is an array before checking the count

[Core] fix bugs in Tracking Extractors 

---

src/CoreShop/Bundle/CoreBundle/Application/Version.php

- This release makes CoreShop compatible with Pimcore 5.6.0 (#762)
- Fixes a Bug in the Tracking Manager when a Product doesn't have any categories applied (#767)
- Adds a new CoreShop JS Event to add custom Menu Items to the CoreShop Menu (#765)
- Adds a JMS Serializer Handler for Pimcore Objects (#766)

[Release] 2.0.2

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php

[OrderBundle] add event to prepare sale in order to better extend details

---

src/CoreShop/Bundle/OrderBundle/Resources/translations/admin.en.yml

[OrderBundle] add translations for adjustments

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/WorkflowBundle/DependencyInjection/CoreShopWorkflowExtension.php

[WorkflowBundle, OrderBundle] always load all available coreshop states into js

---

src/CoreShop/Component/Order/Processable/ProcessableOrderItems.php

[Order] make accessor protected for OrderDocument Processor

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
src/CoreShop/Component/Order/Processor/CartItemProcessorInterface.php

This allows to define new Cart Item Calculators and still have a valid tax-calculation.

Cart item processor extract

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/settings.js

[CoreBundle] fix wkhtml invoice settings

---

src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/StoreMailConfigurationType.php

related to https://github.com/symfony/symfony/pull/29911

[CoreBundle] fix store-mail configuration type

---

features/cart/rules/gift_product_action.feature
src/CoreShop/Behat/Context/Domain/CartContext.php
src/CoreShop/Behat/Context/Setup/CartContext.php
src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
src/CoreShop/Bundle/CoreBundle/Report/AbandonedCartsReport.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
src/CoreShop/Bundle/OrderBundle/Form/Type/CartItemType.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
src/CoreShop/Component/Core/Shipping/Rule/Condition/ProductsConditionChecker.php
src/CoreShop/Component/Order/Cart/CartModifier.php
src/CoreShop/Component/Order/Cart/Rule/CartPriceRuleUnProcessor.php
src/CoreShop/Component/Order/Cart/Rule/ProposalCartPriceRuleCalculator.php
src/CoreShop/Component/Order/Factory/CartItemFactory.php
src/CoreShop/Component/Order/Factory/CartItemFactoryInterface.php
src/CoreShop/Component/Order/Model/Cart.php

[#795] fix cart-rule action gift product and add behat tests for it

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

[CoreBundle] implement dirty detection for store-price

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

Revert "[CoreBundle] implement dirty detection for store-price"

---

src/CoreShop/Behat/Context/Domain/CurrencyContext.php
src/CoreShop/Behat/Context/Domain/ExchangeRateContext.php
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Context/Domain/ProductContext.php
src/CoreShop/Behat/Context/Domain/ShippingContext.php
src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
src/CoreShop/Behat/Context/Setup/ExchangeRateContext.php
src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
src/CoreShop/Behat/Context/Setup/ProductSpecificPriceRuleContext.php
src/CoreShop/Behat/Context/Setup/ShippingContext.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
src/CoreShop/Bundle/CoreBundle/Report/CarriersReport.php
src/CoreShop/Bundle/CoreBundle/Report/PaymentProvidersReport.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
src/CoreShop/Component/Index/Interpreter/SoundexInterpreter.php
src/CoreShop/Component/Index/Worker/FilterGroupHelper.php

[All] replace intval with (int), casting is way faster than intval

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

Store price dirty detection

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
src/CoreShop/Component/Resource/Doctrine/Type/PimcoreAsset.php
src/CoreShop/Component/Resource/Doctrine/Type/PimcoreDocument.php
src/CoreShop/Component/Resource/Doctrine/Type/PimcoreSite.php

[Resource] add more doctrine-pimcore-types

---

src/CoreShop/Bundle/FixtureBundle/README.md

| Fixed tickets | nope
Just fixed a not working link.

Fix dead link

---

src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/OrderState.php

Fix State Labels

---

src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
src/CoreShop/Bundle/CoreBundle/Report/CustomersReport.php
src/CoreShop/Bundle/CoreBundle/Report/ManufacturerReport.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/abstract.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/categories.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/customers.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/manufacturer.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/products.js

Reports Grid Sorting

---

src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php

[Core] fix for cart-item digital product never set

---

src/CoreShop/Component/Core/Order/Calculator/PurchasableProductDiscountPriceCalculator.php
src/CoreShop/Component/Core/Order/Calculator/PurchasableProductPriceCalculator.php
src/CoreShop/Component/Core/Order/Calculator/PurchasableProductRetailPriceCalculator.php
src/CoreShop/Component/Order/Calculator/CompositePurchasableDiscountPriceCalculator.php
src/CoreShop/Component/Order/Calculator/CompositePurchasablePriceCalculator.php
src/CoreShop/Component/Order/Calculator/CompositePurchasableRetailPriceCalculator.php
src/CoreShop/Component/Order/Calculator/PurchasableCalculator.php
src/CoreShop/Component/Order/Calculator/PurchasableDiscountPriceCalculatorInterface.php
src/CoreShop/Component/Order/Calculator/PurchasablePriceCalculator.php
src/CoreShop/Component/Order/Calculator/PurchasablePriceCalculatorInterface.php
src/CoreShop/Component/Order/Calculator/PurchasableRetailPriceCalculatorInterface.php
src/CoreShop/Component/Order/Exception/NoPurchasableDiscountPriceFoundException.php
src/CoreShop/Component/Order/Exception/NoPurchasablePriceFoundException.php
src/CoreShop/Component/Order/Exception/NoPurchasableRetailPriceFoundException.php
src/CoreShop/Component/Product/Calculator/CompositeDiscountCalculator.php
src/CoreShop/Component/Product/Calculator/CompositeDiscountPriceCalculator.php
src/CoreShop/Component/Product/Calculator/CompositeRetailPriceCalculator.php
src/CoreShop/Component/Product/Calculator/ProductDiscountPriceCalculatorInterface.php
src/CoreShop/Component/Product/Calculator/ProductPriceCalculator.php
src/CoreShop/Component/Product/Calculator/ProductRetailPriceCalculatorInterface.php
src/CoreShop/Component/Product/Exception/NoDiscountPriceFoundException.php
src/CoreShop/Component/Product/Exception/NoPriceFoundException.php
src/CoreShop/Component/Product/Exception/NoRetailPriceFoundException.php
src/CoreShop/Component/Product/Rule/Calculator/ProductPriceRuleCalculator.php

[Core, Order, Product] throw exceptions for when a price can't be found

---

src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php

[Order] fix code-generator length

---

src/CoreShop/Bundle/ResourceBundle/Form/Type/PimcoreResourceSelectionType.php

[ResourceBundle] fix for resource selection type

---

src/CoreShop/Component/Order/Transformer/OrderDocumentItemTransformerInterface.php
src/CoreShop/Component/Order/Transformer/OrderItemToInvoiceItemTransformer.php
src/CoreShop/Component/Order/Transformer/OrderItemToShipmentItemTransformer.php
src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php

[Order] introduce options for order-document-items

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderInvoiceController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderShipmentController.php
src/CoreShop/Bundle/OrderBundle/Form/Type/OrderInvoiceCreationItemsType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/OrderInvoiceCreationType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/OrderShipmentCreationItemsType.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_shipment.yml
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js

[OrderBundle] change creation of OrderShipments and OrderInvoices

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/shipment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js

[OrderBundle, CoreBundle] revise create-shipment/create-invoice form in extjs

---

src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_invoice.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_order.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_payment.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/workflow/coreshop_shipment.yml

[OrderBundle] remove usage of deprecated order-state-history service

---

features/filter/order/simple_order.feature
src/CoreShop/Behat/Context/Domain/FilterContext.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterOrderRendererTypesPass.php
src/CoreShop/Bundle/IndexBundle/Order/Mysql/AbstractMysqlDynamicRenderer.php
src/CoreShop/Bundle/IndexBundle/Order/Mysql/SimpleOrderRenderer.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/order_renderer.yml
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Listing/OrderAwareListingInterface.php
src/CoreShop/Component/Index/Order/DynamicOrderRendererInterface.php
src/CoreShop/Component/Index/Order/OrderInterface.php
src/CoreShop/Component/Index/Order/OrderRenderer.php
src/CoreShop/Component/Index/Order/OrderRendererInterface.php
src/CoreShop/Component/Index/Order/SimpleOrder.php

by using the same method as we do with conditions

[Index] introduce advanced sorting

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig

[Frontend] remove unused property in detail template

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig

[Checkout] validate cart before submitting the order

---

src/CoreShop/Bundle/AddressBundle/Form/Type/CountryChoiceType.php
src/CoreShop/Bundle/AddressBundle/Form/Type/StateChoiceType.php
src/CoreShop/Bundle/AddressBundle/Form/Type/ZoneChoiceType.php
src/CoreShop/Bundle/CurrencyBundle/Form/Type/CurrencyChoiceType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/IndexChoiceType.php
src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierChoiceType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/ShippingRuleChoiceType.php
src/CoreShop/Bundle/StoreBundle/Form/Type/StoreChoiceType.php
src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRateChoiceType.php
src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRuleGroupChoiceType.php

[All] remove PHP5 quick fix for sorts

---

src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php

[Core] if cart has no shippables, don't force carriage calculation

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_addToCart.html.twig
src/CoreShop/Bundle/OrderBundle/DTO/AddToCart.php
src/CoreShop/Bundle/OrderBundle/DTO/AddToCartInterface.php
src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactory.php
src/CoreShop/Bundle/OrderBundle/Factory/AddToCartFactoryInterface.php
src/CoreShop/Bundle/OrderBundle/Form/Type/AddToCartType.php
src/CoreShop/Component/Order/Cart/CartModifier.php
src/CoreShop/Component/Order/Factory/CartItemFactory.php
src/CoreShop/Component/Order/Factory/CartItemFactoryInterface.php
src/CoreShop/Component/StorageList/SimpleStorageListModifier.php
src/CoreShop/Component/StorageList/StorageListModifierInterface.php

Refactor add to cart

---

src/CoreShop/Behat/Resources/config/suites/domain/theme.yml

[Behat] the cart tests haven't been ran since the theme-bundle was introduced

---

src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/admin.yml

don't load menu via compiled resources -> load it direct

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Core/Model/ProductInterface.php

[SaleUnit] introduce a more easier function to get store-values

---

src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php
src/CoreShop/Bundle/MenuBundle/Renderer/JsonRenderer.php

[MenuBundle] introduce sorting of menu entries

---

src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php

[MenuBundle] fix product price rules menu entry

---

src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php

dont use private method in product controller

---

src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/OrderMailConfigurationType.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Action/StoreMailConfigurationType.php

[CoreBundle] fix notification rule settings for order mail action

---

src/CoreShop/Component/Core/Product/Calculator/StoreProductPriceCalculator.php

remove usage of store-price in favour of new storeValues

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190226122625.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionsType.php
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinition.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js
src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php

fix unit collection persistance behaviour

---

features/order/customer_deletion.feature
src/CoreShop/Behat/Context/Domain/CustomerContext.php
src/CoreShop/Behat/Resources/config/suites/domain/order.yml
src/CoreShop/Bundle/CoreBundle/EventListener/CustomerOrderDeletionListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php

| Bug fix?      | yes and no
| New feature?  | yes and no
| Fixed tickets | #707

Disable Customer Deletion if bounded Orders are available

---

src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartStockAvailabilityValidator.php
src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php

[CoreBundle] fix cart-stock validation

---

src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js

Check Unit Definition Layout Availability Before Processing

---

src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Form/Type/ProductQuantityPriceRuleType.php

[ProductQuantityPriceRules] make calculation behaviour required

---

src/CoreShop/Bundle/NotificationBundle/Resources/config/serializer/Model.NotificationRule.yml

Fix NotificationRule Model Namespace Typo

---

src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_order.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml

as this breaks how stacks are supposed to work. And it also doesn't make any sense

[Core] don't overwrite interfaces

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

[CoreBundle] fix bug in assigning store-values

---

CHANGELOG-2.0.x.md
features/order/create_order_with_discount.feature
src/CoreShop/Behat/Resources/config/suites/domain/order.yml
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuoteItem.json

[Adjustments] fix typo in OrderItem and QuoteItem

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190327132707.php
src/CoreShop/Bundle/ProductBundle/Doctrine/ORM/PriceRuleRepository.php
src/CoreShop/Bundle/ProductBundle/Doctrine/ORM/ProductPriceRuleRepository.php
src/CoreShop/Bundle/ProductBundle/Form/Type/ProductPriceRuleType.php
src/CoreShop/Bundle/ProductBundle/Form/Type/ProductSpecificPriceRuleType.php
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRule.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.PriceRuleTranslation.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductPriceRule.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductPriceRuleTranslation.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductSpecificPriceRule.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.ProductSpecificPriceRuleTranslation.yml
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/item.js
src/CoreShop/Component/Product/Model/AbstractPriceRule.php
src/CoreShop/Component/Product/Model/PriceRuleInterface.php
src/CoreShop/Component/Product/Model/ProductSpecificPriceRule.php
src/CoreShop/Component/Product/Model/ProductSpecificPriceRuleInterface.php
src/CoreShop/Component/Product/Repository/PriceRuleRepositoryInterface.php
src/CoreShop/Component/Product/Repository/ProductPriceRuleRepositoryInterface.php
src/CoreShop/Component/Product/Repository/ProductSpecificPriceRuleRepositoryInterface.php

[PriceRules] add priority to product-price-rules

---

src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml

[ProductBundle] re-add active to list serializer group

---

src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/AddressIdentifierRepository.php
src/CoreShop/Bundle/AddressBundle/Form/Type/AddressType.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Component/Address/Repository/AddressIdentifierRepositoryInterface.php

[AddressBundle] AddressIdentifier Follow-up

---

src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.ProductStoreValues.yml

[CoreBundle] serialize relational values (product and store) as relation

---

src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_customer.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_order.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_product.yml

Revert "[Core] don't overwrite interfaces"

---

.travis.yml
composer.json
phpstan.neon
src/CoreShop/Bundle/CoreBundle/composer.json
src/CoreShop/Bundle/ProductBundle/composer.json
src/CoreShop/Component/Pimcore/BCLayer/LazyLoadedFields.php

[Pimcore] make CoreShop 2.0 compatible with Pimcore 5.7.2

---

src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartAvailability.php
src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartRecalculation.php
src/CoreShop/Bundle/OrderBundle/EventListener/SessionCartSubscriber.php

Ignore Symfony Toolbar Requests by default.

Ignore Toolbar Route

---

src/CoreShop/Component/Core/Order/Transformer/CartToSaleTransformer.php

`$sale->setAdditionalData($cart->getAdditionalData());` is evil since it transfers:
`Pimcore\Model\DataObject\CoreShopCart\AdditionalData` into the `CoreShopOrder` Object instead of using the `Pimcore\Model\DataObject\CoreShopOrder\AdditionalData` ObjectBrick Class.

Clone AdditionalData Line By Line

---

.travis.yml
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Context/Hook/PimcoreDaoContext.php
src/CoreShop/Behat/Resources/config/services/contexts/hook.yml
src/CoreShop/Bundle/AddressBundle/composer.json
src/CoreShop/Bundle/ConfigurationBundle/composer.json
src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/composer.json
src/CoreShop/Bundle/CurrencyBundle/composer.json
src/CoreShop/Bundle/CustomerBundle/composer.json
src/CoreShop/Bundle/IndexBundle/composer.json
src/CoreShop/Bundle/MoneyBundle/composer.json
src/CoreShop/Bundle/NotificationBundle/composer.json
src/CoreShop/Bundle/OrderBundle/composer.json
src/CoreShop/Bundle/PaymentBundle/composer.json
src/CoreShop/Bundle/PayumBundle/composer.json
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductBundle/composer.json
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
src/CoreShop/Bundle/ResourceBundle/composer.json
src/CoreShop/Bundle/StoreBundle/composer.json
src/CoreShop/Bundle/ThemeBundle/composer.json
src/CoreShop/Bundle/TrackingBundle/composer.json
src/CoreShop/Bundle/WorkflowBundle/composer.json
src/CoreShop/Component/Locale/composer.json
src/CoreShop/Component/Pimcore/composer.json
src/CoreShop/Component/Resource/composer.json

[Pimcore] make CoreShop 2.1 compatible with Pimcore 5.7.2

---

src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/AddressIdentifierRepository.php

only return single address identifier in repository

---

src/CoreShop/Bundle/AddressBundle/Resources/config/serializer/Model.Country.yml
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/country/panel.js

change it on the server as well, so we also display the fallback for other country field types as well
| Fixed tickets | #937

[AddressBundle] follow-up on #939

---

src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductUnitFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductWithUnitFixture.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinition.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.yml

Introduce Product Unit Fixtures. This also fixes a bug to create UnitDefinitions on an PHP API Level.

Product Unit fixtures

---

src/CoreShop/Component/Core/Product/Calculator/StoreProductUnitDefinitionPriceCalculator.php

If no store values has been defined but only quantity ranges, an exception raises. This PR fixes that issue.

check store values availability

---

src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Core/Model/QuantityRangeInterface.php
src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRangePriceAwareInterface.php

add missing interface definitions

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190418150640.php
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRuleTranslation.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRuleTranslation.orm.yml
src/CoreShop/Component/Product/Model/AbstractPriceRule.php
src/CoreShop/Component/Resource/Model/TranslatableTrait.php
src/CoreShop/Component/Rule/Model/RuleTrait.php

[Product][#952] allow price rule labels to be null and fix error with two trait constructors

---

composer.json
src/CoreShop/Bundle/CoreBundle/Controller/PortletsController.php
src/CoreShop/Bundle/CoreBundle/Controller/ReportsController.php
src/CoreShop/Bundle/ResourceBundle/composer.json
src/CoreShop/Bundle/RuleBundle/Resources/config/pimcore/config.yml

[Serializer] Update JMS Serializer Bundle to 2.0

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoneyCurrency.js

[CurrencyBundle] fix money-currency extension

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
src/CoreShop/Component/Currency/Model/Money.php

[Currency] validation fixes for MoneyCurrency

---

src/CoreShop/Component/Core/Model/Category.php

[Core] strip_tags for meta description in category

---

src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStorePriceRepository.php

[CoreBundle] remove result cache for store price -> it causes issues with inheritance

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php

[CurrencyBundle] MoneyCurrency Type: Don't check validity when empty and not mandatory.

---

src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
src/CoreShop/Bundle/IndexBundle/Installer.php
src/CoreShop/Bundle/IndexBundle/Menu/IndexMenuBuilder.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services/installer.yml
src/CoreShop/Bundle/IndexBundle/composer.json

[IndexBundle] improve standalone usage

---

src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Bundle/SEOBundle/CoreShopSEOBundle.php
src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php

[Bundles] provide proper version strings and names

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190503073647.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_rules.html.twig
src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/OrderBundle/Form/Type/CartPriceRuleTranslationType.php
src/CoreShop/Bundle/OrderBundle/Resources/config/doctrine/model/CartPriceRuleTranslation.orm.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.CartPriceRule.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.CartPriceRuleTranslation.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
src/CoreShop/Component/Order/Model/CartPriceRule.php
src/CoreShop/Component/Order/Model/CartPriceRuleInterface.php
src/CoreShop/Component/Order/Model/CartPriceRuleTranslation.php
src/CoreShop/Component/Order/Model/CartPriceRuleTranslationInterface.php

[#968] introduce translatable cart-price-rules

---

features/cart/cart_taxation_gross_rounding.feature
src/CoreShop/Component/Core/Cart/Rule/Applier/DiscountApplier.php
src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
src/CoreShop/Component/Taxation/Collector/TaxCollector.php
src/CoreShop/Component/Taxation/Collector/TaxCollectorInterface.php

[Taxation] fix tax collection on gross values

---

features/cart/cart_taxation_gross_rounding.feature
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
src/CoreShop/Component/Taxation/Collector/TaxCollector.php
src/CoreShop/Component/Taxation/Collector/TaxCollectorInterface.php

| Fixed tickets | #971
Same PR as #972 just for 2.1 (master) branch

[Taxation] fix tax collection on gross values - 2.1

---

src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml

[CoreBundle] persist customer on login if the cart has an id

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/serializer/Carbon.yml

[ResourceBundle] don't serialize Carbon

---

src/CoreShop/Component/Core/Inventory/Operator/OrderInventoryOperator.php

use default unit quanity in onhold inventory

---

src/CoreShop/Component/Pimcore/DataObject/Migrate.php

[Pimcore] fix stan tests

---

src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json

to not trigger pimcore validations

[ProductBundle, CoreBundle] set itemQuantityFactor min value to null

---

src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php

[ResourceBundle] add connection interface into Pimcore Repository

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Listing/ListingInterface.php

[Index, IndexBundle] allow options for the listing load function

---

features/cart/rules/discount_amount_action_tax.feature
features/cart/rules/discount_percent_action_tax.feature
features/cart/rules/surcharge_amount_action.feature
features/cart/rules/surcharge_percent_action.feature
src/CoreShop/Behat/Context/Domain/CartContext.php
src/CoreShop/Behat/Context/Setup/CartPriceRuleContext.php
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php

[Core] fix cart-rule-applier tax calculation when used with surcharge

---

src/CoreShop/Bundle/ResourceBundle/Installer/Configuration/ImageThumbnailConfiguration.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php

| Fixed tickets |   ---
The thumbnails can now be assigned to a group.

Add group to ThumbnailInstaller

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php

[CurrencyBundle] fix for money-currency editable when data comes from pimcore editmode

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

[CoreBundle] fix inheritance for store-values

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php

[PimcoreBundle] use reflection to get class methods

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/dynamic_dropdown.yml

[PimcoreBundle] fix dynamic-dropdown for pimcore-6

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/actions/storeMail.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/payment/provider/item.js
src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/actions/mail.js

[All] fix related to element.href and this pimcore PR: pimcore/pimcore#4496

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SerializedData.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnit.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php

[CoreExtensions] don't allow any diff until properly implemented 2.1

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
src/CoreShop/Bundle/OrderBundle/EventListener/CheckoutCartLocaleAssignerListener.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/checkout_listener.yml
src/CoreShop/Component/Order/CheckoutEvents.php
src/CoreShop/Component/Order/Event/CheckoutEvent.php

| Bug fix?      | yes and no
| Fixed tickets | #652 
Introduces new Events into the Checkout and also fixes #652 to set the right locale just before we create the order.

[Order] introduce checkout events

---

src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductSpecificPriceRules.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js

[ProductBundle] specific price rules: keep id on save

---

.travis.yml
features/tracking/analytics_enhanced.feature
features/tracking/global_site_tag.feature
features/tracking/tag_manager_classic.feature
features/tracking/tag_manager_enhanced.feature
features/tracking/universal_ecommerce.feature
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Matomo/Matomo.php
src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php

fix total tax in tag manager tracker

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js

[IndexBundle] fix iterator and nested interpreter

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/tracking.yml
src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php

Add Decimal Precision to Order Extractor

---

composer.json

https://github.com/pimcore/pimcore/pull/4835

[Pimcore] add conflict for Pimcore 6.1.0 and Pimcore 6.1.1

---

src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php

[ResourceBundle] fix resource-select options

---

.travis.yml
src/CoreShop/Bundle/CoreBundle/Controller/SettingsController.php

fix stan and travis tests

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/validators.yml

[FQCN] add service alias for QuantityValidatorService

---

features/cart/cart_units_precision.feature
src/CoreShop/Behat/Context/Setup/CartContext.php
src/CoreShop/Behat/Context/Setup/ProductContext.php
src/CoreShop/Component/Product/Model/ProductUnitDefinition.php

add tests for product units, also make precision default to 0

---

.gitignore
.travis.yml
etc/_setup/install
features/placeholder/expression.feature
src/CoreShop/Behat/Context/Setup/ProductContext.php

[Tests] set default precision to 0

---

features/product/product_store_values_inheritance.feature
src/CoreShop/Behat/Context/Domain/ProductContext.php
src/CoreShop/Behat/Context/Hook/PimcoreDaoContext.php
src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
src/CoreShop/Behat/Context/Setup/ProductContext.php
src/CoreShop/Behat/Context/Transform/ProductContext.php
src/CoreShop/Behat/Resources/config/suites/domain/product.yml
src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190911143118.php
src/CoreShop/Component/Core/Model/ProductStoreValues.php

Store Values - default value to 0 instead of null, fix setting inherited store values

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

[IndexBundle] allow for more complex doctrine types in index

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml

[FQCN] add aliases for resource installers

---

etc/suites/application
etc/suites/codestyle
etc/suites/stan

[Tests] exit code

---

src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/productQuantityPriceRules/ranges.js

allow price range ordering

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml

[FQCN] makes aliases for resource installers public

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20191009093444.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierType.php
src/CoreShop/Bundle/ShippingBundle/Resources/config/doctrine/model/Carrier.orm.yml
src/CoreShop/Bundle/ShippingBundle/Resources/config/serializer/Model.Carrier.yml
src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/item.js
src/CoreShop/Component/Shipping/Model/Carrier.php
src/CoreShop/Component/Shipping/Model/CarrierInterface.php

Associate Pimcore Asset with the Carrier as a logo.

[Shipping, ShippingBundle] Add logo field to carrier

---

src/CoreShop/Component/Core/Tracking/Extractor/OrderExtractor.php

remove decimal factor multiplier in order extractor

---

CHANGELOG-2.0.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.0.10] prepare release

---

src/CoreShop/Bundle/ThemeBundle/composer.json

[ThemeBundle] add missing dependency to pimcore-bundle

---

src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdownMultiple.js

fix naming of parameter sortBy

---

src/CoreShop/Bundle/ThemeBundle/composer.json

[ThemeBundle] use pimcore-bundle 2.1

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

[IndexBundle] use doctrine schema-config to create index-table schema

---

src/CoreShop/Bundle/CoreBundle/EventListener/QuantityRangeUnitValidationListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Event/ProductQuantityPriceRuleValidationEvent.php
src/CoreShop/Component/ProductQuantityPriceRules/Events.php

Check Inherited Product Quantity Price Range Data

---

src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/country/item.js
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
tests/lib/CoreShop/Test/PHPUnit/Suites/Country.php

[AddressBundle] Improve Country Address Formatting

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing/Dao.php
src/CoreShop/Component/Index/Listing/ExtendedListingInterface.php

[IndexBundle] allow to query relations also by relation type

---

src/CoreShop/Bundle/SEOBundle/DependencyInjection/Compiler/ExtractorRegistryServicePass.php
src/CoreShop/Bundle/SEOBundle/Resources/config/services.yml
src/CoreShop/Component/SEO/SEOPresentation.php

[SEOBundle] add priority to extractors

---

src/CoreShop/Bundle/StoreBundle/composer.json

[StoreBundle] add missing store dependency

---

src/CoreShop/Bundle/FixtureBundle/composer.json
src/CoreShop/Bundle/ResourceBundle/composer.json

[FixtureBundle, ResourceBundle] bump framework-bundle to use at least 3.4.26 or 4.1.12

---

src/CoreShop/Bundle/CoreBundle/Installer.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version00000001.php

[Install] add dummy migration

---

.travis.yml
composer.json

[Tests] add conflict for monolog and tests against Pimcore 6.3

---

src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopEmbeddedClass.js

On create of a new entry "general" is needed further down the line.

---

.travis.yml
src/CoreShop/Bundle/CoreBundle/Customer/CustomerLoginService.php
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/security.yml

[Symfony4.4] fixes

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

[StoreValues] make sure we properly break inheritance when child product store values change

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/paginator.html.twig

Fix Paginator with search queries

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20191122074934.php
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
src/CoreShop/Component/Order/Model/CartItem.php

[Core, Order] fix calculation with Cart Item Adjustments

---

src/CoreShop/Bundle/CoreBundle/Form/Extension/AddToCartTypeExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_item.html.twig
src/CoreShop/Bundle/OrderBundle/Form/Type/AddToCartType.php

[Cart] properly validate also cart-item validation rules

---

etc/_scripts/composer

[Tests] fix tests for Pimcore dev-master, don't validate composer if we test against pimcore/pimcore:dev-master

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/validators.yml
src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartQuantityValidator.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Component/Order/Cart/CartItemResolver.php
src/CoreShop/Component/Order/Cart/CartModifier.php
src/CoreShop/Component/StorageList/SimpleStorageListModifier.php
src/CoreShop/Component/StorageList/StorageListItemModelEqualsResolver.php
src/CoreShop/Component/StorageList/StorageListItemResolverInterface.php

[StorageList] introduce service to resolve if cart-items are equal

---

src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js

This PR allows us to add some additional data to each item row:

Allow Item Data per Row in Order Overview

---

src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Events.php

[OrderBundle] add sale-detail event

---

src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php

[#1198] fix item price for items without tax-rule

---

src/CoreShop/Bundle/FrontendBundle/Controller/SecurityController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/customer.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Security/_login-form.html.twig

[FrontendBundle] add failure_path to login_form

---

src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml

[FrontendBundle] add trailing $ to routes

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/preview.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice/render.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment/render.js

[CoreBundle] remove usage of addCsrfTokenToUrl

---

etc/_scripts/composer
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php

[Tests] fix tests

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/services/form.yml

complete unclosed service declaration

---

src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php

[ThemeBundle] fix Undefined index: default_resolvers

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php

[CurrencyBundle] fix money-currency type is rounding prices wrong

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php

The function is now reusable for controllers extending the `CheckoutController`.

[FrontendBundle] Change function from private to protected

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig

Remove duplicate condition in template

---

src/CoreShop/Bundle/IndexBundle/Form/Type/Worker/MysqlWorkerTableIndexType.php

[IndexBundle] fix index columns form

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/context.yml
src/CoreShop/Component/Core/Cart/CartContextResolver.php
src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartItemsWholesaleProcessor.php
src/CoreShop/Component/Order/Cart/CartContextResolver.php
src/CoreShop/Component/Order/Cart/CartContextResolverInterface.php

[Cart] introduce cart-context resolver to allow better extendability of the context used for the cart

---

src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
src/CoreShop/Component/Address/Context/RequestBased/CachedCountryContext.php
src/CoreShop/Component/Address/Context/RequestBased/CountryContext.php
src/CoreShop/Component/Address/Context/RequestBased/GeoLiteBasedRequestResolver.php

[Country] don't call the request based resolvers every time

---

etc/geoipupdate/CHANGELOG.md
etc/geoipupdate/GeoIP.conf
etc/geoipupdate/GeoIP.conf.md
etc/geoipupdate/LICENSE-APACHE
etc/geoipupdate/LICENSE-MIT
etc/geoipupdate/README.md
etc/geoipupdate/geoipupdate.md
features/country/country_context.feature
src/CoreShop/Behat/Context/Domain/CountryContext.php
src/CoreShop/Behat/Context/Setup/CountryContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Bundle/AddressBundle/Resources/config/services.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/context.yml
src/CoreShop/Component/Address/Context/RequestBased/GeoLiteBasedRequestResolver.php
src/CoreShop/Component/Core/Cart/CartContextResolver.php
src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartItemsWholesaleProcessor.php
src/CoreShop/Component/Order/Cart/CartContextResolver.php
src/CoreShop/Component/Order/Cart/CartContextResolverInterface.php

[Address, Order, Core] fix release

---

src/CoreShop/Component/Index/Worker/WorkerInterface.php

Should make phpstan happier :)

Change return type of WorkerInterface::getList

---

src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php

[ThemeBundle] fix default theme-resolvers

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml

[CoreBundle] fix shipping rule action discount-amount

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.1.4] prepare release

---

CHANGELOG-2.2.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.2.0-RC.1] prepare release

---

src/CoreShop/Bundle/AddressBundle/Controller/CountryController.php
src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/AddressBundle/Resources/config/pimcore/routing.yml
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js

| Fixed tickets | #1298 
Previous PR: https://github.com/coreshop/CoreShop/pull/1299

[AddressBundle] introduce filter-active action and filter store-base countries by those

---

src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php

[ThemeBundle] fix configuration for default resolvers

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml

[CoreBundle] fix typo in validation groups and fix guest-registration type

---

features/index/index_relational_extension.feature
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Resources/config/services.yml
src/CoreShop/Behat/Service/CustomRelationalIndexInterpreter.php
src/CoreShop/Behat/Service/RelationalIndexExtension.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Component/Index/Extension/IndexRelationalColumnsExtensionInterface.php
src/CoreShop/Component/Index/Interpreter/RelationalValue.php

[IndexBundle] add possibility to store extra information into relational table

---

app/config/config_behat.yml
composer.json
src/CoreShop/Bundle/AddressBundle/composer.json
src/CoreShop/Bundle/ConfigurationBundle/composer.json
src/CoreShop/Bundle/CoreBundle/composer.json
src/CoreShop/Bundle/CurrencyBundle/composer.json
src/CoreShop/Bundle/CustomerBundle/composer.json
src/CoreShop/Bundle/IndexBundle/composer.json
src/CoreShop/Bundle/MenuBundle/composer.json
src/CoreShop/Bundle/MoneyBundle/composer.json
src/CoreShop/Bundle/NotificationBundle/composer.json
src/CoreShop/Bundle/OrderBundle/composer.json
src/CoreShop/Bundle/PaymentBundle/composer.json
src/CoreShop/Bundle/PayumBundle/composer.json
src/CoreShop/Bundle/ProductBundle/composer.json
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
src/CoreShop/Bundle/ResourceBundle/composer.json
src/CoreShop/Bundle/StoreBundle/composer.json
src/CoreShop/Bundle/ThemeBundle/composer.json
src/CoreShop/Bundle/TrackingBundle/composer.json
src/CoreShop/Bundle/WorkflowBundle/composer.json
src/CoreShop/Component/Locale/composer.json
src/CoreShop/Component/Pimcore/composer.json
src/CoreShop/Component/Resource/composer.json

| Bug fix?      | yes 
Not adding this also breaks the tests. Gotta be something with translations cache or something.

[Pimcore] Compatibility with Pimcore 6.5.3

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php

[Doctrine] remove usage of deprecated merge

---

docs/03_Development/03_Products/06_Unit_Definitions.md
docs/03_Development/03_Products/README.md

Adds some documentation for Unit Definitions

Add Documentation for Unit Definitions

---

src/CoreShop/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
src/CoreShop/Bundle/ResourceBundle/Installer/AbstractTranslationInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcorePermissionInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php

[Installer] change installer colors

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/abstract.js

[Reports] fix export params #839

---

CHANGELOG-2.2.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.2.0-RC.2] release

---

src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

| New feature?  | yes/
| Fixed tickets | #1318

[Order] don't allow order-revise when completed payment has been made

---

.github/workflows/behat.yml
.travis.yml
composer.json
src/CoreShop/Bundle/AddressBundle/composer.json
src/CoreShop/Bundle/ConfigurationBundle/composer.json
src/CoreShop/Bundle/CoreBundle/composer.json
src/CoreShop/Bundle/CurrencyBundle/composer.json
src/CoreShop/Bundle/CustomerBundle/composer.json
src/CoreShop/Bundle/IndexBundle/composer.json
src/CoreShop/Bundle/MenuBundle/composer.json
src/CoreShop/Bundle/MoneyBundle/composer.json
src/CoreShop/Bundle/NotificationBundle/composer.json
src/CoreShop/Bundle/OrderBundle/composer.json
src/CoreShop/Bundle/PaymentBundle/composer.json
src/CoreShop/Bundle/PayumBundle/composer.json
src/CoreShop/Bundle/ProductBundle/composer.json
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/composer.json
src/CoreShop/Bundle/ResourceBundle/composer.json
src/CoreShop/Bundle/StoreBundle/composer.json
src/CoreShop/Bundle/ThemeBundle/composer.json
src/CoreShop/Bundle/TrackingBundle/composer.json
src/CoreShop/Bundle/WorkflowBundle/composer.json
src/CoreShop/Component/Locale/composer.json
src/CoreShop/Component/Pimcore/composer.json
src/CoreShop/Component/Resource/composer.json

[Pimcore] require min 6.6

---

src/CoreShop/Bundle/CoreBundle/EventListener/CustomerSecurityValidationListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml

[SecurityValidator] only trigger when Pimcore Frontend request

---

src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js

[OrderBundle] show price rules without tax in backend

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/store/item.js

[CoreBundle][2.1] Fix name of country combo

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.1.6] prepare release

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml

[CoreBundle] add missing alias for taxed product price calculator

---

src/CoreShop/Component/Pimcore/DataObject/DataLoader.php

[Pimcore] fix getDataForEditmode

---

src/CoreShop/Bundle/ThemeBundle/Service/InheritanceLocator.php

[ThemeBundle] fix for inheritance locator when no theme is set

---

src/CoreShop/Bundle/ThemeBundle/EventListener/ThemeRequestListener.php
src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml

not sure if that 100% fixes it. here is the BC break: https://github.com/pimcore/pimcore/pull/5905

[ThemeBundle] fix pimcore bc-break

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail/blocks/carriage.js
src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Controller/CartController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/detail/blocks/detail.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editInvoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/products.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/panel.js

[Order] use Javascript intl for currency format

---

src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml

[Product] serialize stopPropogation property

---

src/CoreShop/Bundle/CoreBundle/Controller/ProductPreviewController.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js
src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/PimcoreRepository.php
src/CoreShop/Component/Core/Model/CategoryInterface.php
src/CoreShop/Component/Core/Model/PimcoreStoresAwareInterface.php
src/CoreShop/Component/Core/Model/ProductInterface.php
src/CoreShop/Component/Resource/Pimcore/Model/PimcoreModelInterface.php

[FrontendBundle] allow preview from admin-mode and redirect to right URL if wrong

---

src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionPriceType.php
src/CoreShop/Component/Product/Model/ProductUnitDefinitionPrice.php

[Product] fix null value for pricing #1362

---

src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/panel.js

[ResourceBundle] ignore length for name of CoreShop doctrine assets (also fixes the error on cancel)

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js

[CoreBundle] only show restore-inheritance when actually inheritable

---

src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/shipment.html.twig

Fix customer address display on shipment

---

src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/invoice.html.twig

Fix customer address display on invoice

---

src/CoreShop/Component/Pimcore/DataObject/DataLoader.php

Backport fix getDataForEditmode #1361

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.1.7] prepare release

---

src/CoreShop/Bundle/AddressBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/MoneyBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/PaymentBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/ShippingBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/StoreBundle/Resources/config/services/data_hub.yml
src/CoreShop/Bundle/TaxationBundle/Resources/config/services/data_hub.yml

[DataHub] fix integration

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php

[FrontendBundle] revert url-forward, doesn't work for all cases

---

docs/02_Bundles/Index_Bundle.md

Fix typo in the docs

---

src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/PaymentType.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/SummaryType.php
src/CoreShop/Bundle/CoreBundle/Form/Type/GuestRegistrationType.php

[CoreBundle] fix validation groups

---

src/CoreShop/Bundle/CoreBundle/Customer/RegistrationService.php

[CoreBundle] fix registration service

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.1.8] prepare release

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js
src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js

[QuantityPriceRules] fix decimal precision display

---

app/config/config_test_precision.yml
features/ui/product/view_product_with_precision.feature
src/CoreShop/Behat/Service/ConfigurationBasedDisplayFractionProvider.php
src/CoreShop/Bundle/CurrencyBundle/Resources/config/services.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/twig.yml
src/CoreShop/Bundle/CurrencyBundle/Twig/ConvertCurrencyExtension.php
src/CoreShop/Bundle/CurrencyBundle/Twig/DisplayFractionExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/currency.html.twig
src/CoreShop/Component/Currency/Display/DefaultDisplayFractionProvider.php
src/CoreShop/Component/Currency/Display/DisplayFractionProviderInterface.php

[3.0] introduce currency fraction display provider service

---

src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php

[CurrencyBundle] fix cache issue with money-currency type

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/condition.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/nested.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/item.js
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/productQuantityPriceRules/object/item.js
src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/action.js
src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/condition.js
src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/conditions/nested.js
src/CoreShop/Bundle/RuleBundle/Resources/public/pimcore/js/rules/item.js

[RuleBundle] improve dirty detection

---

src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php

This PR fix typo in query condition to fetch product variants

[CoreBundle] fix typo in query condition to fetch product variants

---

src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/documents.yml
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

This PR add the italian translations into FrontendBundle

[FrontendBundle] add italian translations

---

src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php

[IndexBundle] fix range filter condition

---

src/CoreShop/Bundle/IndexBundle/Resources/config/validation/FilterCondition.yml

[IndexBundle] fix saving of nested filters

---

src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php

[Installer] fix output of thumbnail installer

---

features/product/price_rules/quantity_condition.feature
src/CoreShop/Behat/Context/Setup/ProductPriceRuleContext.php
src/CoreShop/Behat/Resources/config/suites/domain/product.yml
src/CoreShop/Behat/Resources/config/suites/domain/recycle_bin.yml
src/CoreShop/Behat/Resources/config/suites/domain/version.yml
src/CoreShop/Component/Core/Product/Rule/Condition/QuantityConditionChecker.php

[ProductBundle] fix quantity price rule condition

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_invoice.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/order_shipment.yml
src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php
src/CoreShop/Component/Order/Transformer/OrderToInvoiceTransformer.php
src/CoreShop/Component/Order/Transformer/OrderToShipmentTransformer.php

[All] remove usage of ItemKeyTransformer Service and use DataObject\Service directly

---

src/CoreShop/Bundle/OrderBundle/Command/OrderExpireCommand.php

[OrderBundle] Fix order expire command

---

CHANGELOG-2.2.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.2.2] prepare release

---

composer.json
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/AddressIdentifierFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ConfigurationFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CurrencyFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/NotificationRulesFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/StoreFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/ZoneFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/AbstractProductFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CarrierFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/CategoryFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/PaymentProviderFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductUnitFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductWithUnitFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleGroupFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/TaxRateFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/TaxRuleGroupFixture.php
src/CoreShop/Bundle/FixtureBundle/Fixture/UpdateDataFixturesFixture.php
src/CoreShop/Bundle/FixtureBundle/composer.json

[Fixtures] update fixtures version and fix Deprecation message

---

src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php

[Core] create default address if customer doesn't have one

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php

[FrontendBundle] apply confirm and pay transition for orders with value of 0

---

src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.Sale.yml

[OrderBundle] Add currency property

---

features/domain/cart/rules/discount_amount_action_tax_rounding.feature
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php

[Core] fix calculation of discounts with tax rounding issues

---

src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php

Backport of https://github.com/coreshop/CoreShop/pull/1433/files

[2.2][OrderBundle] Values should be zero, if amount should not be defined

---

src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php

Backport of https://github.com/coreshop/CoreShop/pull/1435

[2.2][Core] create default address if customer doesn't have one

---

src/CoreShop/Bundle/ProductBundle/Resources/config/serializer/Model.AbstractPriceRule.yml

[ProductBundle] fix serialization of translation labels in product-price rules

---

src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php

fix voucher code generator

---

src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php

[CoreBundle] fix installation of address format

---

features/cart/rules/voucher_code_generation.feature
src/CoreShop/Behat/Context/Domain/CartPriceRuleVoucherCodeContext.php
src/CoreShop/Behat/Context/Setup/CartPriceRuleVoucherCodeContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Behat/Resources/config/suites/domain/cart.yml
src/CoreShop/Bundle/CoreBundle/Migrations/Version20200715071804.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php
src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleVoucherRepository.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartPriceRuleVoucherGenerator.yml
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
src/CoreShop/Bundle/OrderBundle/Validator/Constraints/VoucherAmount.php
src/CoreShop/Bundle/OrderBundle/Validator/Constraints/VoucherAmountValidator.php
src/CoreShop/Bundle/ResourceBundle/Form/Helper/ErrorSerializer.php
src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
src/CoreShop/Component/Order/Exception/FailedCodeGenerationException.php
src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php
src/CoreShop/Component/Order/Generator/CodeGeneratorChecker.php
src/CoreShop/Component/Order/Generator/CodeGeneratorCheckerInterface.php
src/CoreShop/Component/Order/Generator/CodeGeneratorLetterResolver.php
src/CoreShop/Component/Order/Repository/CartPriceRuleVoucherRepositoryInterface.php

| Fixed tickets | #1453 
TODO: test

[OrderBundle] check if generation of a certain amount of codes is possible before actually generating them

---

src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/SurchargeAmountConfigurationType.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/surchargeAmount.js
src/CoreShop/Component/Core/Cart/Rule/Action/SurchargeAmountActionProcessor.php

[Core, Order] fix surchage amount processor and remove apply-on

---

src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
src/CoreShop/Bundle/OrderBundle/Controller/CartEditController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderCreationController.php

[OrderBundle] fix usage of inherited values in backend-cart/order controllers

---

src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php

[EntityMerger] reset state of newData

---

src/CoreShop/Bundle/OrderBundle/Controller/CartCreationController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderCreationController.php
src/CoreShop/Bundle/OrderBundle/Controller/QuoteCreationController.php

[OrderBundle] fix permission keys for order-creation

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/actions/additionAmount.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/shipping/rules/actions/price.js
src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Action/SurchargePercentConfigurationType.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/discountAmount.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/discountPercent.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/surchargeAmount.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/actions/surchargePercent.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/conditions/amount.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/createPayment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/actions/discountAmount.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/actions/discountPercent.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/pricerule/actions/price.js
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionPercentActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountPercentActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/actions/additionPercent.js
src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/shippingrule/conditions/amount.js

[All] allow percentage with scale of 2 and respect decimal_precision for rules

---

src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterImplementationLoaderPass.php

[Pimcore] fix hasDefinition with pimcore.implementation_loader.document.tag

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js

Fix Pseudo Price in Grid-View in QPR

---

src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/base.js

[OrderBundle, LocaleBundle] fix backend order-creation localeCode selection

---

src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php

[Core] pass cart-item to price calculation context

---

features/index/index_column_config_extension.feature
src/CoreShop/Behat/Context/Domain/IndexContext.php
src/CoreShop/Behat/Resources/config/services.yml
src/CoreShop/Behat/Service/Index/IndexColumnExtension.php
src/CoreShop/Behat/Service/Index/RelationalIndexExtension.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Component/Index/Extension/IndexColumnTypeConfigExtension.php
src/CoreShop/Component/Index/Extension/IndexSystemColumnTypeConfigExtension.php

[Index] allow to define column config with index-extensions

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

[CoreBundle] fix setting price-values for inherited store-values

---

.github/workflows/behat.yml
composer.json
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php

[Pimcore 6.8] make Stan compatible with Pimcore 6.8

---

CHANGELOG-2.2.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

[2.2.5] prepare release

---

src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php

[CoreBundle] interactive login: cart might not be available for several reasons, ignore exception and don't assign a cart

---

src/CoreShop/Component/Locale/composer.json

[Locale] Fix PSR-4 namespace

---

src/CoreShop/Bundle/ThemeBundle/EventListener/ThemeRequestListener.php
src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml

[Theme] resolve theme only if not in admin

---

src/CoreShop/Component/Pimcore/DataObject/AbstractSluggableLinkGenerator.php

fix return empty string if $string is null

---

src/CoreShop/Component/Core/Notification/Rule/Condition/StoresChecker.php

fix return of store on notification rule

---

.scrutinizer.yml

[Scruitinizer] try fixing it

---

.github/workflows/stan.yml

correct stan action

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php

[DynmicDropdown] support class override and fix order by id

---

src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Bundle/ResourceBundle/AbstractResourceBundle.php
src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
src/CoreShop/Bundle/SEOBundle/CoreShopSEOBundle.php
src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php

[composer2] make getVersion compatible

---

src/CoreShop/Bundle/CoreBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php

[Orders] Carrier name not shown with legacy serialization

---

src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php

[Order] fix payment provider

---

src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php

[ProductBundle] fix UnitDefinition without id

---

src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php

[ResourceBundle] fix object-manager

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php

https://github.com/coreshop/CoreShop/pull/1555/files @lorextera

[PimcoreBundle] fix sorting for DynamicDropdown 

---

src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php

[OptimisticEntityLockBundle] fix Version loading with Composer v3

---

src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml

fix decoration

---

src/CoreShop/Component/Address/Model/Country.php
src/CoreShop/Component/Address/Model/State.php
src/CoreShop/Component/Product/Model/ProductUnit.php
src/CoreShop/Component/Taxation/Model/TaxRate.php

[Models] strict defining of model trait methods

---

src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php

[OptimisticEntityLockBundle] fix version for Pimcore Extensions UI

---

src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopCart.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuote.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopCart.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoice.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoiceItem.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipment.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuote.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js
src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/object/elementHref.js

[All] replace all usages of href with manyToOneRelation and multihref with manyToManyRelation

---

src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php

[ResourceBundle] fix compatibility with Doctrine EventSubscriber

---

src/CoreShop/Bundle/CoreBundle/Command/InstallResourcesCommand.php
src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js
src/CoreShop/Bundle/ResourceBundle/Installer/AbstractTranslationInstaller.php
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/object/elementHref.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/object/objectMultihref.js

[3.0] Pimcore BC

---

src/CoreShop/Bundle/PaymentBundle/CoreExtension/PaymentProviderMultiselect.php
src/CoreShop/Bundle/PaymentBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/coreExtension/data/coreShopPaymentProviderMultiselect.js
src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopPaymentProviderMultiselect.js
src/CoreShop/Bundle/PaymentBundle/Resources/translations/admin.de.yml
src/CoreShop/Bundle/PaymentBundle/Resources/translations/admin.en.yml

[PaymentBundle] Add PaymentProvider Multiselect CoreExtension

---

src/CoreShop/Component/Address/Formatter/AddressFormatter.php

Will remove empty lines in the address

prevent empty lines in address formatter

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/AddressCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/CustomerCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/PaymentCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/ShippingCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php

[FrontendBundle] use named forms where applicable

---

src/CoreShop/Bundle/CustomerBundle/Resources/translations/validators.it.yml
src/CoreShop/Bundle/InventoryBundle/Resources/translations/validators.it.yml

Add italian translations for validators in InventoryBundle & CustomerBundle

Add italian translations for validators

---

src/CoreShop/Bundle/PaymentBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopPaymentProviderMultiselect.js

[PaymentBundle] Fix provider multiselect

---

docs/03_Development/12_Customers/01_CRUD.md

Change typo in create a new customer

Fixed typo

---

src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php

[Fixtures] fix region_short for address format

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php

[FrontendBundle] fix having unique form-ids for cart add

---

docs/02_Bundles/Index_Bundle.md

[IndexBundle] Add missing process conditions in docs

---

src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php
src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml

[ThemeBundle] fix loading of theme when in Pimcore Admin

---

src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCompany.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopCustomerBundle/CoreShopCustomer.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrder.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderShipment.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderInvoice.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderShipment.json
src/CoreShop/Bundle/ProductBundle/Resources/install/pimcore/classes/CoreShopProduct.json
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelation.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/data/coreShopRelations.js

[ResourceBundle] fix height for coreShopRelations type

---

src/CoreShop/Bundle/TrackingBundle/DependencyInjection/CoreShopTrackingExtension.php

[Tracking] enable auto-configuration and auto-wiring with configuration

---

src/CoreShop/Bundle/AddressBundle/Collector/CountryCollector.php
src/CoreShop/Bundle/AddressBundle/Resources/config/services/profiler.yml
src/CoreShop/Bundle/CoreBundle/Collector/CurrencyCollector.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/profiler.yml
src/CoreShop/Bundle/StoreBundle/Collector/StoreCollector.php
src/CoreShop/Bundle/StoreBundle/DependencyInjection/CoreShopStoreExtension.php
src/CoreShop/Bundle/StoreBundle/Resources/config/services/profiler.yml

[Profiling] disable coreshop profiles in backend

---

src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php
src/CoreShop/Bundle/OrderBundle/Doctrine/ORM/CartPriceRuleVoucherRepository.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/pricerules/item.js
src/CoreShop/Component/Order/Repository/CartPriceRuleVoucherRepositoryInterface.php

[OrderBundle] fix pagination in voucher codes and add pagination for csv export

---

src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ShippingRuleFixture.php

[CoreBundle] remove zones from shipping rules installer

---

src/CoreShop/Bundle/IndexBundle/EventListener/UpdateIndexListener.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Worker/WorkerInterface.php

[IndexBundle] add feature to rename tables when index get's renamed

---

.github/workflows/behat.yml

[Tests] Add Pimcore ~6.9.0 in behat test matrix

---

src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php

[Stan] fix validation error

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20210614115749.php
src/CoreShop/Bundle/IndexBundle/Controller/FilterController.php
src/CoreShop/Bundle/IndexBundle/Form/DataMapper/ConditionsFormMapper.php
src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterPreConditionNestedType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterUserConditionNestedType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterConditionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterPreConditionCollectionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterUserConditionCollectionType.php
src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.xml
src/CoreShop/Bundle/IndexBundle/Resources/config/serializer/Model.Index.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/condition.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/nested.js
src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php
src/CoreShop/Component/Index/Model/FilterCondition.php
src/CoreShop/Component/Index/Model/FilterConditionInterface.php

[Index] Fix merge for index-conditions

---

features/ui/frontend/checkout/checkout_with_cart_price_rule_free_shipping.feature
src/CoreShop/Component/Order/Modifier/VoucherModifier.php

[Order] fix voucher modifier with empty voucher code

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_item.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/_widget.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_list.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_item.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_preview.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Quote/show.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig

[FrontendBundle] fix images html output

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190605141526.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20200415152607.php
src/CoreShop/Bundle/IndexBundle/Migrations/Version20200224161101.php

[CoreBundle] AbstractPimcoreMigration leftover

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig

[FrontendBundle] Macro "price" is not defined in template

---

src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php

[CoreBundle] Use right permission for tax rate

---

src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml
src/CoreShop/Component/SEO/Extractor/ImageExtractor.php

[SEO - ImageExtractor] Add thumbnail definition `coreshop_seo`

---

composer.json

Require released version of Pimcore X

[Pimcore] Use Pimcore ^10.0

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20210721112600.php
src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.yml
src/CoreShop/Component/Index/Model/FilterCondition.php
src/CoreShop/Component/Index/Model/FilterConditionInterface.php

Throws column "sort" not found on category pages.

[IndexBundle] Fix sort column on condition

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/data_hub.yml

[CoreBundle] fix with datahub enabled

---

README.md

[3.x] Fix demo link in README

---

bin/subtree-release
src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/ProductRepository.php

Was a pull request some time ago. So this is "The Return of the Jed...", I mean: This is a new try ;-)

[Core] Fix: ProductRepository: Added missing placeholder

---

src/CoreShop/Bundle/CustomerBundle/Resources/public/pimcore/js/customer_group/list.js

[CustomerBundle] fix CustomerGroup List route

---

src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php

fix: Error on updating cart vouchers

---

features/domain/cart/cart_units_precision_change.feature
src/CoreShop/Behat/Context/Setup/CartContext.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderEditController.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartItemTaxProcessor.php
src/CoreShop/Component/Order/Distributor/FloatDistributor.php
src/CoreShop/Component/Order/Distributor/FloatDistributorInterface.php
src/CoreShop/Component/Order/Factory/OrderItemFactory.php
src/CoreShop/Component/Order/Factory/OrderItemFactoryInterface.php
src/CoreShop/Component/Taxation/Calculator/TaxCalculatorInterface.php
src/CoreShop/Component/Taxation/Collector/TaxCollector.php

[Core] optimize Tax Calculation in Units

---

src/CoreShop/Bundle/CoreBundle/Installer.php

[CoreBundle] fix Installer

---

features/ui/frontend/cart/automatic_cart_price_rule_gift_registration.feature
src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php

[Core] gift price rule: check if cart-item was persisted before trying to delete it

---

src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js

[PimcoreBundle] super-select box readonly

---

src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopSuperBoxSelect.js

[PimcoreBundle] super-select box readonly 3.x

---

composer.json
src/CoreShop/Bundle/CoreBundle/composer.json

[Faker] use fakerphp/faker

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Listing/ListingInterface.php

[Index] remove dbal connection in AbstractListing

---

src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php
src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Compiler/RemoveThemeAwareTranslatorPass.php

[ThemeBundle] remove sylius theme-aware-translator, that doesn't work well with Pimcore

---

src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopUserBundle/CoreShopUser.json
src/CoreShop/Bundle/CustomerBundle/Resources/install/pimcore/classes/CoreShopCustomer.json
src/CoreShop/Bundle/UserBundle/Resources/install/pimcore/classes/CoreShopUser.json

[User] remove md5 password and use password_hash

---

src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php

fix: Error when creating new order manually

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Bundle/OrderBundle/Context/SessionAndStoreBasedCartContext.php
src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php
src/CoreShop/Component/Index/Listing/ListingInterface.php

[Index] make ListingInterface a Pimcore PaginateListingInterface

---

src/CoreShop/Bundle/CoreBundle/Installer.php

[Installer] use settings-store-aware installer

---

src/CoreShop/Bundle/CustomerBundle/CoreExtension/Provider/RoleOptionsProvider.php

[CustomerBundle] move RoleOptionsProvider from User to Customer Bundle

---

composer.json
src/CoreShop/Bundle/ResourceBundle/composer.json

[JMS] Update to 4.x bundle

---

src/CoreShop/Behat/Context/Setup/IndexConditionContext.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/RangeRenderer.php
src/CoreShop/Component/Index/Condition/RangeCondition.php
src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php

[IndexBundle] fix for range conditions

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/RangeRenderer.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractListing.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php
src/CoreShop/Component/Index/Listing/ListingInterface.php

[Index] remove setCategory from IndexInterface

---

src/CoreShop/Component/Tracking/Tracker/CompositeTracker.php

| Fixed tickets | fixes #1728
@dkarlovi like this?

[Tracking] Composite increase performance

---

src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrateCommand.php
src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrationGenerateCommand.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml

For easier execution and creation of app-migrations

[PimcoreBundle] add coreshop:migration:migrate  and coreshop:migration:generate

---

src/CoreShop/Bundle/AddressBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCountry.js
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopState.js
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/coreExtension/document/coreShopZone.js
src/CoreShop/Bundle/CurrencyBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCurrency.js
src/CoreShop/Bundle/IndexBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/coreExtension/document/coreShopFilter.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/coreExtension/document/coreShopIndex.js
src/CoreShop/Bundle/PaymentBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/PaymentBundle/Resources/public/pimcore/js/coreExtension/document/coreShopPaymentProvider.js
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterPimcoreDocumentTagImplementationLoaderPass.php
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterPimcoreDocumentTagPass.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Document/Select.php
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/coreExtension/document/select.js
src/CoreShop/Bundle/ShippingBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/coreExtension/document/coreShopCarrier.js
src/CoreShop/Bundle/StoreBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/coreExtension/document/coreShopStore.js
src/CoreShop/Bundle/TaxationBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/document/coreShopTaxRate.js
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/document/coreShopTaxRuleGroup.js

[All] rename document coreshop editables

---

src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js

[FrontendBundle] Fix "Invoice Address is Shipping Address" in checkout address step

---

src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php

add is_null in isNewEntity

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_boolean.html.twig
src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionBooleanType.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/boolean.js
src/CoreShop/Component/Index/Filter/BooleanFilterConditionProcessor.php

[IndexBundle] add boolean filter condition

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/multiselect.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/range.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/relational_multiselect.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/relational_select.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/select.js

[IndexBundle] add clear button for filter preSelect combos

---

src/CoreShop/Bundle/OrderBundle/EventListener/SessionCartSubscriber.php

[OrderBundle] fix session cart subscriber when no session is available

---

src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js

[ResourceBundle] fix resource list calling Pimcore Event and CoreShop Event to open object

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20220117153741.php
src/CoreShop/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml
src/CoreShop/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php
src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml

[Payment] fix for PayPal payment

---

src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js

[List] fix open CoreShop Entry and Pimcore DataObject

---

src/CoreShop/Bundle/IndexBundle/Installer.php
src/CoreShop/Bundle/IndexBundle/Migrations/Version20220121154623.php

This PR implements the `SettingsStoreAwareInstaller` for the `CoreShopIndexBundle`.

[IndexBundle] Migrate to SettingsStoreAwareInstaller

---

src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php
src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml

[Theme] fallback to SettableThemeContext

---

src/CoreShop/Bundle/PimcoreBundle/EventListener/SluggableListener.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services.yml
src/CoreShop/Component/Pimcore/Exception/SlugNotPossibleException.php
src/CoreShop/Component/Pimcore/Slug/SluggableSlugger.php
src/CoreShop/Component/Pimcore/Slug/SluggableSluggerInterface.php

[PimcoreBundle] added SluggableSlugger for SluggableListener

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php
src/CoreShop/Component/Pimcore/DataObject/AbstractDefinitionUpdate.php
src/CoreShop/Component/Pimcore/DataObject/BrickDefinitionUpdate.php
src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php
src/CoreShop/Component/Pimcore/DataObject/ClassUpdateInterface.php
src/CoreShop/Component/Pimcore/DataObject/FieldCollectionDefinitionUpdate.php

[Pimcore] Definition Updater: check if we should use 'childs' or 'children'

---

src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php

[Core] address assignment manager should check for null

---

src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Component/Index/Extension/DecimalIndexColumnTypeConfigExtension.php

[IndexBundle] decimal should be 10,2

---

src/CoreShop/Bundle/IndexBundle/Form/Type/FilterConditionType.php

[IndexBundle] QuantityValue ID's are strings

---

src/CoreShop/Bundle/TaxationBundle/CoreExtension/TaxRate.php
src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/TaxationBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/TaxationBundle/Resources/install/pimcore/fieldcollections/CoreShopTaxItem.json
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/css/taxation.css
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/data/coreShopTaxRate.js
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopTaxRate.js
src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
src/CoreShop/Component/Taxation/Collector/TaxCollector.php
src/CoreShop/Component/Taxation/Model/TaxItemInterface.php

[Taxation] add taxRate to TaxItemInterface

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/QuoteListener.php

[CoreBundle] fix quote notification sending

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml
src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php

[FrontendBundle] fix createQuoteAction

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190605141526.php

Fix Version20190605141526

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php

[CoreBundle] fix user-reset password notification sending

---

src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/exchangeRate/panel.js

[CurrencyBundle] fix exchange rate saving/deleting

---

src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php

[ResourceBundle] fix entity-merger to delete collection entries

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php

[IndexBundle] fixed issue 1891, fix totalCount for pagination

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter/_category_select.html.twig

Since it is called "CategorySelect" it should only allow to select one category

Category select template fix

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/resource.js

[CoreBundle] don't load settings if user has no permission

---

src/CoreShop/Bundle/OrderBundle/Renderer/OrderDocumentPdfRenderer.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/controller.yml

Fixes invoices PDF tab. Bug due to changes in the way controllers are saved on documents in Pimcore X

Generating invoice PDF fix

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/invoice/invoiceState.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/payment/paymentState.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/shipment/shipmentState.js

In notification rules conditions were broken  for payment, shipment and invoice state.

Fixed invoice, payment, shipment state condition in notifications

---

src/CoreShop/Component/Core/Context/ShopperContext.php
src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/AmountDecreaseAction.php
src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/AmountIncreaseAction.php
src/CoreShop/Component/Core/ProductQuantityPriceRules/Rule/Action/FixedAction.php
src/CoreShop/Component/Core/Shipping/Rule/Action/AdditionAmountActionProcessor.php
src/CoreShop/Component/Core/Shipping/Rule/Action/DiscountAmountActionProcessor.php
src/CoreShop/Component/Core/Shipping/Rule/Action/PriceActionProcessor.php
src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculator.php
src/CoreShop/Component/Order/Cart/CartContextResolver.php
src/CoreShop/Component/Product/Rule/Action/DiscountAmountActionProcessor.php
src/CoreShop/Component/Product/Rule/Action/DiscountPriceActionProcessor.php
src/CoreShop/Component/Product/Rule/Action/PriceActionProcessor.php

Values have been converted twice from selected currency to base currency. This change converts all values to the store-currency (=base-currency) and then to the target-currency.

[Conversion] fix currency conversion

---

src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php

[FrontendBundle] fix configuration for controller names

---

src/CoreShop/Bundle/ThemeBundle/Service/ThemeHelper.php

[ThemeHelper] check if theme is not null before setting

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedlocalized.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedrelational.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/objectproperty.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/objecttype/abstract.js

[IndexBundle] don't lower-case interpreter types

---

src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterConditionCategoryMultiSelectType.php
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/abstract.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/conditions/category_multiselect.js
src/CoreShop/Component/Index/Filter/CategoryMultiSelectConditionProcessor.php

| Bug fix?      | yes/
| Fixed tickets | #1899
I had a tipo in last commit. Also added logic for preselecting multiple categories.

Category multiselect filter condition.

---

src/CoreShop/Bundle/PimcoreBundle/Command/AppMigrationGenerateCommand.php

[PimcoreBundle] make command "coreshop:app:migration:generate" not hidden

---

src/CoreShop/Bundle/CoreBundle/Command/InstallCommand.php
src/CoreShop/Bundle/CoreBundle/Installer.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/commands.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/pimcore_installer.yml

[Installer] mark migrations as migrated in the installer

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20220323072817.php
src/CoreShop/Bundle/IndexBundle/Resources/config/doctrine/model/FilterCondition.orm.xml
src/CoreShop/Bundle/IndexBundle/Resources/config/serializer/Model.FilterCondition.yml
src/CoreShop/Component/Index/Filter/BooleanFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/MultiselectFilterConditionFromMultiselectProcessor.php
src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php
src/CoreShop/Component/Index/Filter/RelationalSelectConditionProcessor.php
src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php
src/CoreShop/Component/Index/Filter/SelectFilterConditionProcessor.php
src/CoreShop/Component/Index/Model/FilterCondition.php
src/CoreShop/Component/Index/Model/FilterConditionInterface.php

[IndexBundle] fix saving quantity values for index conditions

---

src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/action.js
src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/condition.js

[NotificationBundle] fix reloading of Notification Conditions/Actions

---

src/CoreShop/Component/Pimcore/Slug/SluggableInterface.php
src/CoreShop/Component/Pimcore/Slug/SluggableSlugger.php

[Slug] fallback to ID if nameForSlug is null

---

src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php

[ResourceBundle] fix creating static routes

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Register/password-reset-request.html.twig

[FrontendBundle] fix styling of reset-password-request submit button

---

src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php

[ProductBundle] fix ProductUnitDefinition unmarshal

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml

[Routing] fix route name coreshop_cart_create_quote

---

src/CoreShop/Component/Registry/PriorityMap.php

fix: PHP 8.1 deprecations

---

src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php

Fix redirect to profile if customer is present

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
src/CoreShop/Bundle/MoneyBundle/Resources/public/pimcore/js/coreExtension/data/coreShopMoney.js

[MoneyBundle] allow Money to be nullable

---

src/CoreShop/Bundle/NotificationBundle/Resources/public/pimcore/js/rule/actions/mail.js

[NotificationBundle] fix saving multiple emails

---

src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
src/CoreShop/Component/Core/Repository/ProductStoreValuesRepositoryInterface.php

[CoreBundle] fix ProductStoreValuesRepository return type

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_update.html.twig

[FrontendBundle] fix add gift product to cart

---

src/CoreShop/Bundle/AddressBundle/Form/Type/AddressIdentifierChoiceType.php
src/CoreShop/Bundle/AddressBundle/Form/Type/CountryChoiceType.php
src/CoreShop/Bundle/AddressBundle/Form/Type/StateChoiceType.php
src/CoreShop/Bundle/AddressBundle/Form/Type/ZoneChoiceType.php
src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/CarrierChoiceType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/ShippingRuleChoiceType.php
src/CoreShop/Bundle/StoreBundle/Form/Type/StoreChoiceType.php
src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRateChoiceType.php
src/CoreShop/Bundle/TaxationBundle/Form/Type/TaxRuleGroupChoiceType.php
src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
src/CoreShop/Component/Store/Context/RequestBased/PimcoreAdminSiteBasedRequestResolver.php

[Store] add Store Resolver for document save from Pimcore Admin

---

src/CoreShop/Bundle/IndexBundle/Form/Type/FilterType.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/routing.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelation.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelations.php
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/item.js
src/CoreShop/Bundle/ResourceBundle/Routing/Configuration.php
src/CoreShop/Bundle/ResourceBundle/Routing/ResourceLoader.php

[ResourceBundle] add feature to clone resources

---

src/CoreShop/Component/Index/Filter/MultiselectFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/RelationalMultiselectConditionProcessor.php

[IndexBundle] fix Argument #2 ($values) must be of type array, string given

---

src/CoreShop/Component/Rule/Condition/RuleConditionsValidationProcessor.php

[Condition] fix rules being active even if inactive when having no conditions

---

src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php

[ResourceBundle] fix ResourceSettingsController getConfigAction

---

src/CoreShop/Bundle/CoreBundle/Validator/Constraints/RegisteredUserValidator.php

[CoreBundle] fix registered user validator

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml

| Fixed tickets | #1987 
Fix typo in notification.yml for QuoteStateConfigurationType

Fix Typo in notifcation.yml

---

src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/list.js

Fix for grid view breaks after grid columns update for orders/quotes/carts in admin.

FIX grid view for orders/quotes/carts in admin

---

src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php

remove variable variables sign

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml
src/CoreShop/Bundle/CoreBundle/Twig/ProductQuantityPriceRuleRangesPriceExtension.php
src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
src/CoreShop/Component/Core/Cart/Rule/Applier/CartRuleApplier.php
src/CoreShop/Component/Core/Order/Processor/CartItemProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartTaxProcessor.php
src/CoreShop/Component/Core/Product/ProductTaxCalculatorFactory.php
src/CoreShop/Component/Core/Product/ProductTaxCalculatorFactoryInterface.php
src/CoreShop/Component/Core/Product/TaxedProductPriceCalculator.php
src/CoreShop/Component/Core/Shipping/Calculator/TaxedCarrierPriceRuleCalculator.php
src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyCartItems.php
src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyTaxRule.php
src/CoreShop/Component/Core/Taxation/CachedTaxCalculatorFactory.php
src/CoreShop/Component/Core/Taxation/TaxCalculatorFactory.php
src/CoreShop/Component/Core/Taxation/TaxCalculatorFactoryInterface.php
src/CoreShop/Component/Shipping/Taxation/TaxCalculationStrategyInterface.php

[Taxation] pass context into TaxCalculatorFactory

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php

FIX newsletter double opt in mail not sending

---

src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/plugin/coreshop.plugin.variant.js
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_variants.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/attributes/detail/_select.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/attributes/detail/_text.html.twig

[CoreBundle] fix variant js, added variant select template

---

src/CoreShop/Bundle/NotificationBundle/Resources/config/services.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/price-rules.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/specific-price-rules.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/product-quantity-price-rules.yml
src/CoreShop/Bundle/RuleBundle/DependencyInjection/Compiler/TraceableValidationProcessorPass.php
src/CoreShop/Bundle/RuleBundle/DependencyInjection/CoreShopRuleExtension.php
src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-rules.yml

[Rule] use tags for TraceableRuleConditionsValidationProcessor

---

docs/01_Gettings_Started/00_Installation.md

| Fixed tickets |
Updated Install section while version 3 is in beta.

Update install guide while it is in beta

---

src/CoreShop/Component/SEO/Extractor/ImageExtractor.php

[SEO] Image Extractor should use frontend_prefix if configured

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php

[Frontend] fix getQuantityModifier return type

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

[MoneyBundle] bugfix unmarshalVersion for coreShopMoney

---

src/CoreShop/Bundle/ThemeBundle/Context/ThemeContext.php

SettableThemeContext should have more priority than resolved context

---

src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/routing.yml

[OrderBundle] fix "coreshop_admin_order_find" route

---

composer.json
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js
src/CoreShop/Bundle/MenuBundle/EventListener/PimcoreAdminListener.php
src/CoreShop/Bundle/MenuBundle/Resources/config/services.yml
src/CoreShop/Bundle/MenuBundle/Resources/public/pimcore/js/events.js
src/CoreShop/Bundle/MenuBundle/Resources/views/menu.js.twig
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductSpecificPriceRules.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductQuantityPriceRules.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/events.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource.js

[Events] fix pimcore events BC break

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

[MoneyBundle] bugfix marshalVersion for coreShopMoney

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

[MoneyBundle] bugfix setter code for FieldCollection

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
src/CoreShop/Bundle/CoreBundle/Security/AccessVoter.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CurrencyController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/FrontendBundle/Controller/QuoteController.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_item.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_items.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_rules.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/_widget.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_grid.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/_list.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/addresses.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/orders.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/profile.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/_footer.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/_header.html.twig
src/CoreShop/Bundle/IndexBundle/EventListener/UpdateIndexListener.php
src/CoreShop/Bundle/StorageListBundle/Controller/StorageListController.php
src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
src/CoreShop/Component/Index/Worker/WorkerInterface.php

[AccessManagement] prepare CoreShop for advanced access-management

---

src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
src/CoreShop/Bundle/StorageListBundle/Pimcore/Repository/PimcoreStorageListRepository.php
src/CoreShop/Bundle/WishlistBundle/Pimcore/Repository/WishlistRepository.php
src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php
src/CoreShop/Component/StorageList/Core/Context/SessionAndStoreBasedStorageListContext.php
src/CoreShop/Component/StorageList/Repository/PimcoreStorageListRepository.php
src/CoreShop/Component/StorageList/Repository/PimcoreStorageListRepositoryInterface.php
src/CoreShop/Component/StorageList/Repository/StorageListRepositoryInterface.php

[StorageList] fix CartContext found Order as cart

---

src/CoreShop/Bundle/VariantBundle/Twig/Extension/VariantExtension.php

[Variant] revert nullable callback param

---

composer.json

| Fixed tickets | #2073 
Lock pkg version

fix #2073 by locking pkg version to 4.0.*

---

src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
src/CoreShop/Bundle/CustomerBundle/CoreShopCustomerBundle.php
src/CoreShop/Bundle/FrontendBundle/CoreShopFrontendBundle.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/MenuBundle/CoreShopMenuBundle.php
src/CoreShop/Bundle/OptimisticEntityLockBundle/CoreShopOptimisticEntityLockBundle.php
src/CoreShop/Bundle/PayumPaymentBundle/CoreShopPayumPaymentBundle.php
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Bundle/ResourceBundle/AbstractResourceBundle.php
src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
src/CoreShop/Bundle/SEOBundle/CoreShopSEOBundle.php
src/CoreShop/Bundle/TestBundle/CoreShopTestBundle.php
src/CoreShop/Bundle/ThemeBundle/CoreShopThemeBundle.php

[Bundle] adapt version number display

---

src/CoreShop/Bundle/PayumPaymentBundle/Resources/config/services/payment.yml

[PayumPaymentBundle] fix event based payment provider resolver

---

src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml

[PayumBundle] use Symfony PSR18Client instead of Guzzle 6

---

features/ui/frontend/wishlist/adding_product_to_wishlist.feature
features/ui/frontend/wishlist/remove_product_from_wishlist.feature
src/CoreShop/Behat/Context/Ui/Frontend/WishlistContext.php
src/CoreShop/Behat/Page/Frontend/ProductPage.php
src/CoreShop/Behat/Page/Frontend/ProductPageInterface.php
src/CoreShop/Behat/Page/Frontend/WishlistPage.php
src/CoreShop/Behat/Page/Frontend/WishlistPageInterface.php
src/CoreShop/Behat/Resources/config/services/contexts/ui.yml
src/CoreShop/Behat/Resources/config/services/pages.yml
src/CoreShop/Behat/Resources/config/suites/ui.yml
src/CoreShop/Behat/Resources/config/suites/ui/wishlist.yml
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/_addToWishlist.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig

[Wishlist] add tests and fix routing

---

src/CoreShop/Component/Pimcore/ExpressionLanguage/PHPFunctionsProvider.php

Some common operations to apply to arrays

feat: add array unique, filter functions to Expression language provider

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/PaymentCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
src/CoreShop/Bundle/PaymentBundle/Resources/config/services.yml
src/CoreShop/Bundle/PaymentBundle/Resources/config/services/resolver.yml
src/CoreShop/Component/Payment/Validator/PaymentProviderValidator.php
src/CoreShop/Component/Payment/Validator/PaymentProviderValidatorInterface.php

[Checkout] introduce Payment Provider Validator to check if the selected one is still valid

---

src/CoreShop/Bundle/OrderBundle/Resources/translations/messages.de.yaml
src/CoreShop/Bundle/OrderBundle/Resources/translations/messages.en.yaml
src/CoreShop/Bundle/OrderBundle/Resources/translations/messages.it.yaml

| Fixed tickets | #2108 
Shorten the payment total translations to not exceed the limitation by klarna

2108: Fix Klarna Sofort Error 8018

---

src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/messenger.yml
src/CoreShop/Bundle/MessengerBundle/Controller/ListMessagesController.php
src/CoreShop/Bundle/MessengerBundle/Controller/MessageController.php
src/CoreShop/Bundle/NotificationBundle/Resources/config/pimcore/messenger.yml

[MessengerBundle] fixes

---

src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php

[StorageList] fix storage-list priority

---

src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php
src/CoreShop/Component/Core/Order/Committer/QuoteCommitter.php

[CartPiceRules] fix OrderItem not finding Order with CartItemPriceRules

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/StorageListBundle/Controller/StorageListController.php

feat: keep a reference to the just-removed Product

---

src/CoreShop/Bundle/MessengerBundle/CoreShopMessengerBundle.php
src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/resource.js

[MessengerBundle] standalone fixes

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

[MoneyBundle] fix issue with not-nullable types and null values

---

src/CoreShop/Component/Resource/Doctrine/Type/BigIntIntegerType.php

[Resource] add return types for BigIntIntegerType

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20200206155318.php

Use valid key in user migration

---

src/CoreShop/Component/StorageList/SessionStorageManager.php

Fix `SessionStorageManager`

---

src/CoreShop/Component/Index/Filter/CategoryMultiSelectConditionProcessor.php
src/CoreShop/Component/Index/Filter/CategorySelectConditionProcessor.php
src/CoreShop/Component/Index/Filter/MultiselectFilterConditionFromMultiselectProcessor.php
src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php
src/CoreShop/Component/Index/Worker/FilterGroupHelper.php

check if index value is null before exploding

---

src/CoreShop/Bundle/IndexBundle/EventListener/IndexDeleteObjectListener.php
src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexDeleteMessageHandler.php
src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
src/CoreShop/Bundle/IndexBundle/Messenger/IndexDeleteMessage.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/messenger.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/messenger.yml
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php
src/CoreShop/Component/Index/Model/IndexableInterface.php
src/CoreShop/Component/Index/Service/IndexUpdaterService.php
src/CoreShop/Component/Index/Service/IndexUpdaterServiceInterface.php
src/CoreShop/Component/Index/Worker/WorkerDeleteableByIdInterface.php
src/CoreShop/Component/Index/Worker/WorkerInterface.php

[Index] fix deleting objects from index after they have been deleted

---

src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php

Do not allow negative or 0 cart item quantity

---

config/packages/test/config.yaml
src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
src/CoreShop/Component/Order/CheckoutEvents.php

[Checkout] add pre-payment event

---

.github/workflows/gitsplit.yml
.gitsplit.yml
bin/generate-gitsplit

infra: enable gitsplit cache_url on GHA

---

src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php

[ShippingBundle] allow min.amount from to be 0

---

src/CoreShop/Bundle/CoreBundle/Controller/ProductValidationController.php
src/CoreShop/Bundle/CoreBundle/Report/ProductsReport.php
src/CoreShop/Bundle/ProductBundle/Controller/ProductUnitDefinitionsController.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepository.php
src/CoreShop/Bundle/ResourceBundle/Pimcore/Repository/StackRepositoryInterface.php
src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php

| Fixed tickets | #2194
```php
<?php
declare(strict_types=1);
namespace CoreShop\Bundle\FrontendBundle;
use CoreShop\Bundle\ResourceBundle\Pimcore\Repository\StackRepository;
use CoreShop\Bundle\ResourceBundle\Pimcore\Repository\StackRepositoryInterface;
use CoreShop\Component\Resource\Model\ResourceInterface;
class TestDecorate implements StackRepositoryInterface
{
public function __construct(private StackRepository $stackRepository)
{
}
public function find($id)
{
return $this->stackRepository->find($id);
}
public function findAll()
{
return $this->stackRepository->findAll();
}
public function findBy(array $criteria, ?array $orderBy = null, $limit = null, …
```

[Core] allow decoration of StackRepository

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

set corret store value attributes

---

src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php

[FrontendBundle] sort orders by orderDate and not ID

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20230127064907.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Carrier.orm.xml

[CoreBundle] fix column names for coreshop_carrier_store table

---

src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterImplementationLoaderPass.php

[PimcoreBundle] fix implementation loader

---

src/CoreShop/Bundle/CoreBundle/Pimcore/GridColumnConfig/Operator/StorePrice.php

- Handle NULL price values
| Fixed tickets | #2213

2213: Fix Grid Column Config

---

src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreMailActionProcessor.php

[Core] fix StoreMailActionProcessor

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php

[FrontendBundle] Checkout allow to pass query params from step to step

---

src/CoreShop/Component/Variant/Model/ProductVariantTrait.php

fix sorting in findMainVariant

---

.github/workflows/static.yml
src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
src/CoreShop/Bundle/WishlistBundle/Resources/config/services.yml

[StorageList] fix missing classes

---

src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntityValidator.php

This PR enables the expression language,

re-implement expression evaluation

---

src/CoreShop/Bundle/StorageListBundle/CoreShopStorageListBundle.php
src/CoreShop/Bundle/StorageListBundle/DependencyInjection/Compiler/RegisterAllStorageListsPass.php
src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php

[StorageListBundle] fix loading 'coreshop.context.cart'

---

src/CoreShop/Component/Order/Cart/Rule/Action/CartItemActionProcessor.php

[Order] don't add CartItemPriceRule if not applicable

---

composer.json
src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
src/CoreShop/Bundle/StorageListBundle/EventListener/CacheListener.php
src/CoreShop/Component/Order/Context/CartContext.php

[Cache] disabling caching of StorageLists for better concurrency

---

src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/WishlistRepository.php
src/CoreShop/Bundle/WishlistBundle/Pimcore/Repository/WishlistRepository.php
src/CoreShop/Component/Wishlist/Repository/WishlistRepositoryInterface.php

[Wishlist] Wishlist Expiry for single use

---

src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/coreshop/coreshop_wishlist.yml
src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php
src/CoreShop/Bundle/WishlistBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/WishlistBundle/Resources/config/services.yml
src/CoreShop/Component/StorageList/Context/SessionBasedListContext.php

[StorageList] add default session based context resolver

---

composer.json
src/CoreShop/Bundle/PayumBundle/composer.json
src/CoreShop/Bundle/PayumPaymentBundle/composer.json

[Guzzle] use ^1.0 for guzzle adapter

---

src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php

[FrontendBundle] throw 404 when Reset-Token not found

---

src/CoreShop/Component/Index/Filter/BooleanFilterConditionProcessor.php
src/CoreShop/Component/Index/Filter/SelectFilterConditionProcessor.php
src/CoreShop/Component/Index/Worker/FilterGroupHelper.php

support 'zero' values for filtering (#2278)
