lib/CoreShop/Tool.php

use it to extend coreshop controller in your theme: `\CoreShop\Tool::loadController('Cart');`

loadController() added

---

CHANGELOG.md
README.md
src/CoreShop/Bundle/AdminBundle/CoreShopAdminBundle.php
src/CoreShop/Bundle/AdminBundle/Migrations/Version20171124111923.php
src/CoreShop/Bundle/CoreBundle/CoreShopCoreBundle.php
src/CoreShop/Bundle/CoreBundle/Installer.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/pimcore_installer.yml
src/CoreShop/Bundle/CoreBundle/composer.json
src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
src/CoreShop/Bundle/ResourceBundle/composer.json
tests/bootstrap.php

This PR deprecates the CoreShopAdminBundle and moves responsability to two different places. The AdminBundle was responsible for:
- Pimcore Installer
- Delivering Pimcore Admin JS Resources
This is done now by CoreShopResourceBundle and CoreShopCoreBundle.
**Pimcore Installer**
Moved to CoreShopCoreBundle, the installer only calls ```coreshop:install``` command anyway
**Admin Resources**
CoreShopResourceBundle is already responsible for registration of resource paths (CSS/JS). It now is a Pimcore-Bundle and delivers the corresponding resources. This also makes it easier to use CoreShop Bundles without the suite as the Bundle delivers the resources on its own.

Deprecate CoreShopAdminBundle

---

src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php

The default parameter for generateUrl is UrlGeneratorInterface::ABSOLUTE_PATH, not ABSOLUTE_URL

[FrontendBundle] make reset password url absolute

---

src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
src/CoreShop/Bundle/OrderBundle/Context/CustomerAndStoreBasedCartContext.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/context.yml

This PR will untangle the cart context behaviour. After a order has been placed, `CustomerAndStoreBasedCartContext` will search again for a cart, based on the current user. If a User comes back from a unfinished order for example, a older cart gets applied to user, even if the customer is still in a order process.
With those changes, `CustomerAndStoreBasedCartContext` only tries to find a mapping cart after a user successfully logged in.

CustomerAndStoreBasedCartContext should only get applied in login route

---

src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CurrencyController.php
src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/FrontendBundle/Controller/FrontendController.php
src/CoreShop/Bundle/FrontendBundle/Controller/IndexController.php
src/CoreShop/Bundle/FrontendBundle/Controller/MailController.php
src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php
src/CoreShop/Bundle/FrontendBundle/Controller/QuoteController.php
src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php
src/CoreShop/Bundle/FrontendBundle/Controller/SearchController.php
src/CoreShop/Bundle/FrontendBundle/Controller/SecurityController.php
src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CoreShopFrontendExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
src/CoreShop/Bundle/FrontendBundle/TemplateConfigurator/TemplateConfigurator.php
src/CoreShop/Bundle/FrontendBundle/TemplateConfigurator/TemplateConfiguratorInterface.php

| Fixed tickets | #178
implement TemplateConfigurator to allow views to be loaded from different locations and in different engines. This allows CoreShop to be used with the PHP Engine as well. You can now configure following things:
```
core_shop_frontend:
view_bundle: 'App'
view_suffix: 'php'
```
This changes the template location path to @App and the suffix to php, so for the Cart Summary that would be: '@App/Cart/summary.html.php'

[FrontendBundle] Template Configurator 

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20180323141834.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml
src/CoreShop/Bundle/FrontendBundle/Resources/public/static/js/shop.js
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/ShipmentCalculator/_widget.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Cart/Summary/_items.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Product/detail.html.twig
src/CoreShop/Bundle/OrderBundle/Form/Type/ShippingCalculatorType.php
src/CoreShop/Component/Core/Order/Processor/CartShippingProcessor.php

| Fixed tickets | #370 
This PR adds some UX improvements in cart to get available carriers by adding a new form (`ShippingCalculatorType`).
See it in action here: http://recordit.co/hskjM1mGKE
- If a cart already has some calculated shipment values (happens if customer already has chosen a shipment address and a carrier in the carrier checkout step), the form will **no longer** show up. Otherwise it's quite confusing if there are shipment prices in the cart overview and also a optional carrier selection form
- @dpfaffenbauer as already discussed, there is still some work to do: If a user checks the available carriers within this new form, he should be able to …

Carrier Calculation in Cart

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStorePrice.js

reset original value of store prices on save -> these prohibited to save values after they have been changed once.
| Fixed tickets | #414

[CoreBundle] reset original value of store prices on save

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/OrderBundle/Controller/OrderInvoiceController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderShipmentController.php
src/CoreShop/Bundle/OrderBundle/Renderer/AssetOrderDocumentPdfRenderer.php
src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php
src/CoreShop/Component/Core/Order/OrderMailProcessor.php

| New feature?  | sort of
This PR improves several things during the pdf generation:
- Check if xvfb is installed. if so use it as xserver
- Better tmp handling. before: if wkhtmltopdf is not installed the html tmp files won't get swiped
- Better error handling in shipment / invoice pdf tab. instead of a "invalid pdf" the header returns a valid html exception string
- Better document validation: if shipment / invoice gets modified, invalidate document pdf
- Better development: Do not create rendered asset as long environment is in`dev` mode (rapid development)

wkHtmlToPdf Improvements

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker/Listing.php

Because in current method, will be search in the whole string

Put the categoryId between commas

---

features/placeholder/expression.feature
src/CoreShop/Behat/Context/Domain/PlaceholderContext.php
src/CoreShop/Behat/Context/Transform/SharedStorageContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/suites.yml
src/CoreShop/Behat/Resources/config/suites/domain/placeholder.yml
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Component/Pimcore/ExpressionLanguage/ExpressionLanguage.php
src/CoreShop/Component/Pimcore/ExpressionLanguage/PimcoreLanguageProvider.php
src/CoreShop/Component/Pimcore/Placeholder/Expression.php

Allows you to use placeholders like:
```
%Expression(expression, {'expression' : 'parameter(\'kernel.environment\')'});
```
```
%Expression(expression, {'expression' : 'object(1).getProperty(\'test\')'});
```
```
%Expression(product, {'expression' : 'value.getProperty(\'test\')'});
```
```
%Expression(expression, {'expression' : 'service(\'coreshop.money_formatter\').format(100, \'EUR\', \'en\')'});
```

[ExpressionPlaceholder] implement a Expression Pimcore Placeholder extension

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20180616104008.php
src/CoreShop/Bundle/NotificationBundle/Resources/config/doctrine/model/NotificationRule.orm.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/doctrine/model/CartPriceRule.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductPriceRule.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductSpecificPriceRule.orm.yml

For action classes the join column was named "condition_id" due to a copy-paste error on my side. This fixes that.

[Rules] Fix action join column name

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/shipment.js
src/CoreShop/Component/Order/Processable/ProcessableOrderItems.php

| Fixed tickets | #501
This PR fixes:
- Allow adding shipments regardless of payment state (Only disallowed if order has been cancelled)
- Allow adding invoices regardless of payment state (Only disallowed if order has been cancelled)
- Implement `paymentCreationAllowed`, to prevent payment additions after a order has been completed or cancelled

Processable Items Extension

---

composer.json
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/country.js
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/state.js
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/resource/zone.js
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/resource/currency.js
src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/resource/store.js
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRate.js
src/CoreShop/Bundle/TaxationBundle/Resources/public/pimcore/js/resource/taxRuleGroup.js

Reason for that: since we load resource stores differently now, they don't exist at time of loading this resource combo boxes.

[All] change all resource combo-boxes to load the store 'async'.

---

CHANGELOG.md
src/CoreShop/Behat/Model/Index/TestEnableIndex.php
src/CoreShop/Behat/Model/Index/TestIndex.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Index/Model/IndexableInterface.php

getName could eventually conflict with a Pimcore non-localized name field, therefore we rename ours to getIndexableName to provide support for that. This is a hard BC Break cause there is no possibility to mark it deprecated. 
Also does the same for getEnabled -> getIndexableEnabled

[Index] rename getName/getEnabled to getIndexableName/getIndexableEnabled in IndexableInterface

---

src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php

When using Process Manager or Import Definitions this error occurs when a user tries to delete some elements. 
$this->modelsToRemove returns array of array instead of array.

Fix issue with calling delete on array

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
src/CoreShop/Component/Core/Notification/Rule/Condition/StateTransitionChecker.php
tests/lib/CoreShop/Test/PHPUnit/Suites/NotificationRule.php

| Fixed tickets | #589
Issue was that we have multiple "cancel" states, for order-invoice, order-shipment, order-payment and order-state and the transition checker had no idea for which workflow it should validate it.

[Notification] add actual workflow-name for State Transition Checker

---

src/CoreShop/Component/Core/Cart/Rule/Condition/CarriersConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/CategoriesConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/CountriesConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/CurrenciesConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/CustomerGroupsConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/CustomersConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/ProductsConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/StoresConditionChecker.php
src/CoreShop/Component/Core/Cart/Rule/Condition/ZonesConditionChecker.php
src/CoreShop/Component/Order/Cart/Rule/Condition/AmountConditionChecker.php
src/CoreShop/Component/Order/Cart/Rule/Condition/CartRuleConditionCheckerInterface.php
src/CoreShop/Component/Order/Cart/Rule/Condition/TimeSpanConditionChecker.php
src/CoreShop/Component/Order/Cart/Rule/Condition/VoucherConditionChecker.php

| BC breaks?    | yes, signature change
changed from
```
public function isCartRuleValid(CartInterface $cart, CartPriceRuleInterface $cartPriceRule, CartPriceRuleVoucherCodeInterface $voucher = null, array $configuration)
```
to
```
public function isCartRuleValid(CartInterface $cart, CartPriceRuleInterface $cartPriceRule, ?CartPriceRuleVoucherCodeInterface $voucher, array $configuration)
```

[Order, Core] fix cart rule condition checker signature with opt param

---

src/CoreShop/Bundle/AddressBundle/Collector/CountryCollector.php
src/CoreShop/Bundle/AddressBundle/Resources/views/Collector/country.html.twig
src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartAvailability.php
src/CoreShop/Bundle/CoreBundle/EventListener/RequestCartRecalculation.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/CoreBundle/Resources/views/Collector/currency.html.twig
src/CoreShop/Bundle/OrderBundle/Collector/CartCollector.php
src/CoreShop/Bundle/OrderBundle/Resources/views/Collector/cart.html.twig
src/CoreShop/Bundle/RuleBundle/Resources/views/Collector/rule.html.twig
src/CoreShop/Bundle/StoreBundle/Collector/StoreCollector.php
src/CoreShop/Bundle/StoreBundle/Resources/views/Collector/store.html.twig

| Fixed tickets | #418
We decide on the store-level if it is a configured CoreShop site, if not, we don't execute any reqeust listener tasks. If you need something from the API, we still throw exceptions

[Non-CoreShop-Sites] allow CoreShop to co-exist along none CoreShop Sites

---

features/shipping/default_carrier_customer.feature
src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountAmountConfigurationType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/Action/DiscountPercentConfigurationType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/Condition/AmountConfigurationType.php
src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountAmountConfigurationType.php
src/CoreShop/Bundle/ProductBundle/Form/Type/Rule/Action/DiscountPercentConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionAmountActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/AdditionPercentActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountAmountActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Action/DiscountPercentActionConfigurationType.php
src/CoreShop/Bundle/ShippingBundle/Form/Type/Rule/Condition/AmountConfigurationType.php

Currently it is possible to set percent values that are higher than 100 percent and amount values that are lower than 0

[All] refine constraints for certain conditions/actions

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php

| Fixed tickets | #643 
screenshot of the import screen after the fix is applied:
The storePrice value was `{"1":0196}`

[fix] StorePrice CSV import: check for JSON decode errors

---

src/CoreShop/Bundle/TrackingBundle/Tracker/AbstractEcommerceTracker.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/AnalyticsEnhancedEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/TagManager/TagManagerClassicEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/TagManager/TagManagerEnhancedEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/UniversalEcommerce.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Matomo/Matomo.php

LiipTheme introduced a Bug here, so we decided to change the notation, since the colon notation is not supported in Symfony 4 anymore as well.
https://github.com/liip/LiipThemeBundle/issues/194

[TrackingBundle] fix template notation for tracking

---

CHANGELOG.md
composer.json
docs/02_Bundles/Resource_Bundle/README.md
src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php
src/CoreShop/Bundle/ResourceBundle/EventListener/BodyListener.php
src/CoreShop/Bundle/ResourceBundle/composer.json

| BC breaks?    | not really
Remove the dependency to FOSRestBundle, only thing that was actually used was the BodyListener, therefore it was a bit of a overhead to install a complete bundle just for that. The BodyListener is now provided by CoreShop and is only used if fos-rest is not installed.

[ResourceBundle] remove fos-rest bundle

---

src/CoreShop/Bundle/FixtureBundle/CoreShopFixtureBundle.php
src/CoreShop/Bundle/FixtureBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/FixtureBundle/DependencyInjection/CoreShopFixtureExtension.php
src/CoreShop/Bundle/FixtureBundle/Fixture/Loader/DataFixturesLoader.php
src/CoreShop/Bundle/FixtureBundle/Fixture/UpdateDataFixturesFixture.php
src/CoreShop/Bundle/FixtureBundle/Model/DataFixture.php
src/CoreShop/Bundle/FixtureBundle/Model/DataFixtureInterface.php
src/CoreShop/Bundle/FixtureBundle/Repository/DataFixtureRepository.php
src/CoreShop/Bundle/FixtureBundle/Repository/DataFixtureRepositoryInterface.php
src/CoreShop/Bundle/FixtureBundle/Resources/config/doctrine/model/DataFixture.orm.yml
src/CoreShop/Bundle/FixtureBundle/Resources/config/services.yml
src/CoreShop/Bundle/FixtureBundle/composer.json

The reason for this is to have all CoreShop entities registered as a coreshop resource to change the installer to only create coreshop tables instead of the whole doctrine managed entities.

[FixtureBundle] refactor fixture-bundle to be a resource-bundle

---

src/CoreShop/Bundle/CoreBundle/Installer/Provider/DatabaseSetupCommandsProvider.php
src/CoreShop/Bundle/ResourceBundle/Command/CreateDatabaseTablesCommand.php
src/CoreShop/Bundle/ResourceBundle/Command/DropDatabaseTablesCommand.php

Only install CoreShop related tables on install. This affects installations where other bundles use ORM as well.

[Setup] change setup command to only install CoreShop tables

---

src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

Use `decimal` as column type, because `double` is not registered with `\Doctrine\DBAL\Types\Type::addType()`.

Use decimal as column type instead of double

---

src/CoreShop/Component/Index/Interpreter/TimestampInterpreter.php

Returns the value directly if it already is a instance of `Carbon\Carbon`.

Check if value is instance of Carbon already

---

src/CoreShop/Bundle/CoreBundle/EventListener/Order/OrderMailNoteEventListener.php
src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php

Sending mails via default mail actions in notification rules will remove the recipient note.

Keep notification param in MailActionProcessor

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/abstract.js

When developing custom `FilterConditions` it would be very handy to be able to also define custom names for the field combo box. For example, when you want to query multiple fields of the index.

Add possibility to define a custom name for fields combo box

---

CHANGELOG.md
src/CoreShop/Behat/Context/Domain/IndexConditionContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/AbstractMysqlDynamicRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/CompareRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/ConcatRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/InRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/IsNullRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/IsRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/LikeRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/Mysql/RangeRenderer.php
src/CoreShop/Bundle/IndexBundle/Condition/MysqlRenderer.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterConditionRendererTypesPass.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/condition_renderer.yml
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Component/Index/Condition/ConditionRenderer.php
src/CoreShop/Component/Index/Condition/ConditionRendererInterface.php
src/CoreShop/Component/Index/Condition/DynamicRendererInterface.php

| Fixed tickets | #711 
This allows to register new `ConditionRenderer` and therefore a more dynamic approach to add new Conditions.
This deprecates the `MysqlRenderer` which was actually supposed to be used internally only anyway.

[Index, IndeBundle] allow condition renderers to be registered dynamically

---

src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CountryFixture.php
src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Application/CurrencyFixture.php

Fixes for command `coreshop:fixture:data:load`:
* Country:
* **major fix** - countries weren't correctly installed for locals like en_GB of fr_FR
* minor fix/upgrade - if a country was already active (in case of a 2nd run) leave it active
* Currency:
* similar to Country Fixture - if Currency is already there don't add it a 2nd time (in case of run second time the command and remove a row from coreshop_fixtures_data of course)

Country (mainly) and currency (additionaly) fixtures fixes

---

src/CoreShop/Bundle/ShippingBundle/Resources/public/pimcore/js/carrier/panel.js

Fix for adding new carrier from Admin Panel - without it you needed to write identifier twice (name from first window wasn't filled to the identifier)

Couriers addition fix

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php

When I add 'Store based Mail' action in 'User Reset Password' I get the error during reset password request (dispatch event 'coreshop.customer.request_password_reset'):
`'StoreMailActionProcessor: Store is not set.'`
This PR should fix this.

Fix for StoreMailActionProcessor exception in Notification Rule.

---

features/order/order_workflow_when_invoice_cancelled.feature
features/order/order_workflow_when_shipment_cancelled.feature
src/CoreShop/Bundle/OrderBundle/StateResolver/OrderInvoiceStateResolver.php
src/CoreShop/Bundle/OrderBundle/StateResolver/OrderShippingStateResolver.php

Steps to reproduce:
- Create a Order
- Create a Shipment
- Cancel the Shipment
- Create a new Shipment
- Ship it
- Order state is now stuck in "confirmed"

[OrderBundle] fix order-document state-resolvers when a document is cancelled

---

features/shipping/carrier_with_no_shipping_rules_valid.feature
src/CoreShop/Behat/Context/Domain/ShippingContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Component/Shipping/Checker/CarrierShippingRuleChecker.php

[Shipping] shipping is valid when no shipping rule is configured

---

src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
src/CoreShop/Component/Pimcore/DataObject/DataLoader.php
src/CoreShop/Component/Pimcore/DataObject/DataLoaderInterface.php

[OrderBundle, Pimcore] extract DataLoader from Controller to be used oustide

---

src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleController.php
src/CoreShop/Component/Pimcore/DataObject/DataLoader.php
src/CoreShop/Component/Pimcore/DataObject/DataLoaderInterface.php

[OrderBundle, Pimcore] add data-loader to 2.0 branch and fix for href and multihref

---

src/CoreShop/Bundle/OrderBundle/Pimcore/GridColumnConfig/Operator/PriceFormatter.php

[OrderBundle] check in price-formatter also for currency-aware types

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190122111926.php
src/CoreShop/Bundle/OrderBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/grid_config.yml
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/object/gridcolumn/operator/coreshop_order_state.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/object/gridcolumn/operator/coreshop_price_formatter.js

| BC breaks?    | potentially yes

[OrderBundle] rename Operators to be more CoreShop specific

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

[Index] introduce new abstract function to allow handling array data better for other providers

---

src/CoreShop/Bundle/IndexBundle/Form/Type/Interpreter/IteratorInterpreterType.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedcontainer.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nestedlocalized.js
src/CoreShop/Component/Index/Interpreter/IteratorInterpreter.php

[Index] introduce iterator interpreter

---

src/CoreShop/Component/Pimcore/Twig/Extension/ObjectHelperExtensions.php

Allows to check if object method exists. Native twig implementation `{{ attribute(object, method) is defined }}` sometimes fails and returns `true`, although the method doesn't exist.

[Pimcore] add object_method twig function

---

CHANGELOG-2.0.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

Prepare 2.0.3 release
- Features:
- [All] Replace intval with int cast (https://github.com/coreshop/CoreShop/pull/805)
- [Core] Store Price Dirty Detection if installed Pimcore Version >= 5.5 (https://github.com/coreshop/CoreShop/pull/807)
- [Core] Allow Variants in Product Rule Conditions (https://github.com/coreshop/CoreShop/pull/794)
- [Core] Add Event for Settings (https://github.com/coreshop/CoreShop/pull/785)
- [Core] Extract CartItem Processor (https://github.com/coreshop/CoreShop/pull/784)
- [Core] Decouple Shipping Calculator from Cart (https://github.com/coreshop/CoreShop/pull/783)
- [Order] extract DataLoader into Pimcore Component (https://github.com/coreshop/CoreShop/pull/782)
- [Order] rename Pimcore Grid Operators to be more CoreShop specific …

[Release] 2.0.3

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml
src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreAssetHandler.php
src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreDocumentHandler.php
src/CoreShop/Bundle/ResourceBundle/Serialization/PimcoreSiteHandler.php

[ResourceBundle] add serialization for pimcore types

---

src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php
src/CoreShop/Bundle/CoreBundle/Report/CustomersReport.php
src/CoreShop/Bundle/CoreBundle/Report/ManufacturerReport.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/reports.yml
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/categories.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/customers.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/report/reports/manufacturer.js

Add Paginator To All Reports

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js

[JS] Split JS Helpers into several regions of usability

---

src/CoreShop/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php
src/CoreShop/Bundle/ResourceBundle/Form/DataTransformer/PimcoreResourceDataTransformer.php
src/CoreShop/Bundle/ResourceBundle/Form/Type/PimcoreResourceSelectionType.php

[ResourceBundle] introduce more basic form types

---

CHANGELOG-2.1.x.md
docs/02_Components/StorageList_Component.md
src/CoreShop/Behat/Context/Domain/CartContext.php
src/CoreShop/Behat/Context/Setup/CartContext.php
src/CoreShop/Bundle/CoreBundle/Validator/Constraints/AddToCartAvailabilityValidator.php
src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
src/CoreShop/Bundle/FrontendBundle/Resources/config/services/wishlist.yml
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php
src/CoreShop/Component/Order/Cart/CartModifier.php
src/CoreShop/Component/Order/Model/Cart.php
src/CoreShop/Component/Order/Model/CartItem.php
src/CoreShop/Component/Order/Model/Sale.php
src/CoreShop/Component/Order/Model/SaleInterface.php
src/CoreShop/Component/StorageList/Model/StorageList.php
src/CoreShop/Component/StorageList/Model/StorageListInterface.php
src/CoreShop/Component/StorageList/Model/StorageListItem.php
src/CoreShop/Component/StorageList/Model/StorageListItemInterface.php
src/CoreShop/Component/StorageList/Model/StorageListProductInterface.php
src/CoreShop/Component/StorageList/SessionStorageListModifier.php
src/CoreShop/Component/StorageList/SimpleStorageListModifier.php
src/CoreShop/Component/StorageList/StorageListModifierInterface.php
tests/lib/CoreShop/Test/Data.php
tests/lib/CoreShop/Test/PHPUnit/Suites/Cart.php
tests/lib/CoreShop/Test/PHPUnit/Suites/StorageList.php

| BC breaks?    | YES
| Deprecations? | YES

Refactor how we identify CartItem - Product

---

src/CoreShop/Bundle/PimcoreBundle/CoreExtension/EmbeddedClass.php
src/CoreShop/Component/Pimcore/DataObject/EditmodeHelper.php

The Embedded Classes were not loading because some compatibility errors. Specifically, the `$typename` was missing, a circular reference on the preGet method and the `EditmodeHelper` wasn't populating its attributes as expected.

Make Embedded Class compatible with Pimcore 5.6

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Product/ProductStoreValuesType.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190308133009.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190315140800.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/builder.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/unitPrice.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/productquantitypricerules/ranges.js
src/CoreShop/Bundle/ProductBundle/Controller/ProductUnitDefinitionsController.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductBundle/Doctrine/ORM/ProductUnitDefinitionsRepository.php
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/product-quantity-price-rules.yml

Sale Unit Follow Up

---

src/CoreShop/Component/Core/Tracking/Extractor/ProductExtractor.php

Use Price Calculator Interface in ProductExtractor

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreValues.js
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/product/storevalues/items/price.js

Make StoreValues Extension Inheritable

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Wishlist/summary.html.twig
src/CoreShop/Component/StorageList/Model/StorageList.php
src/CoreShop/Component/StorageList/Model/StorageListInterface.php
src/CoreShop/Component/StorageList/Model/StorageListItem.php
src/CoreShop/Component/StorageList/Model/StorageListItemInterface.php

[StorageList] StorageList are not Pimcore Objects per se

---

src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php

This PR fixes the `_redirect` flag in address checkout which currently is bypassed due the `mapped`form configuration flag.

Address Redirect Fix

---

src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js

This has been fixed in 2.1 but not in 2.0.x.

fix layout crash if price rule is inactive

---

src/CoreShop/Component/Core/Notification/Rule/Action/Order/StoreMailActionProcessor.php

'Do not send to designated recipient' option is ignored for 'Store based Mail'.
This PR should fix this.

Fixed not passing full configuration for Store based Mail.

---

src/CoreShop/Bundle/AddressBundle/Resources/config/serializer/Model.Country.yml
src/CoreShop/Bundle/AddressBundle/Resources/public/pimcore/js/country/panel.js

[AddressBundle] use isoCode fallback if there is no language translation

---

src/CoreShop/Bundle/AddressBundle/Resources/config/doctrine/model/CountryTranslation.orm.yml
src/CoreShop/Bundle/AddressBundle/Resources/config/doctrine/model/StateTranslation.orm.yml
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190410183520.php
src/CoreShop/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxRateTranslation.orm.yml

changed how translations are created if there is none -> CoreShop creates one but if you don't set any value, it might be null. This is not a problem per se, but it is when using relations to it where you have to have a translation cause null is not allowed. This is the case with the store->country relation
| Fixed tickets | #940

[Translations] allow some translations to be null

---

src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/listeners.yml

only recalculate it. Persist happens when customer adds items or goes into checkout anyway
| Fixed tickets | #920

[CoreBundle] don't persist the cart on user-login event

---

src/CoreShop/Bundle/CoreBundle/Form/Extension/ProductQuantityRangeCollectionTypeExtension.php
src/CoreShop/Component/Core/ProductQuantityPriceRules/Calculator/UnitVolumeCalculator.php
src/CoreShop/Component/ProductQuantityPriceRules/Calculator/VolumeCalculator.php

Currently, 1-Step Ranges are not possible (0-1, 1-2). This PR fixes that.

allow one-step ranges

---

CHANGELOG-2.1.x.md
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190425105238.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190425111940.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopOrderItem.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopOrderBundle/CoreShopQuoteItem.json
src/CoreShop/Bundle/CoreBundle/Resources/install/pimcore/classes/CoreShopProductBundle/CoreShopProduct.json
src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
src/CoreShop/Bundle/CurrencyBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopMoneyCurrency.js
src/CoreShop/Bundle/OrderBundle/CoreShopOrderBundle.php
src/CoreShop/Bundle/OrderBundle/DependencyInjection/Compiler/PurchasableWholesalePriceCalculatorsPass.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services/purchasable.yml
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrderItem.json
src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopQuoteItem.json
src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Core/Order/Processor/CartItemsWholesaleProcessor.php
src/CoreShop/Component/Order/Calculator/CompositePurchasableWholesalePriceCalculator.php
src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculator.php
src/CoreShop/Component/Order/Calculator/PurchasableWholesalePriceCalculatorInterface.php
src/CoreShop/Component/Order/Exception/NoPurchasableWholesalePriceFoundException.php
src/CoreShop/Component/Order/Model/PurchasableInterface.php
src/CoreShop/Component/Order/Model/SaleItemInterface.php
src/CoreShop/Component/Order/Transformer/AbstractCartItemToSaleItemTransformer.php

makes it possible to also calculate different wholesale prices with different currencies

[WholesaleCalculator] introduce purchasable wholesale calculator

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190430134834.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStorePrice.orm.yml

[CoreBundle] add index to StorePrice Entity for better performance

---

src/CoreShop/Component/Order/Factory/AdjustmentFactory.php
src/CoreShop/Component/Order/Factory/CartItemFactory.php

remove return type AdjustmentInterface

---

src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php

Since DataObject Properties are not public anymore, Symfony throws an exception that the property is not accessable

[Pimcore] make coreshop compatible with Pimcore 5.8

---

src/CoreShop/Bundle/CoreBundle/Maintenance/ProposalExpireTask.php
src/CoreShop/Bundle/CoreBundle/Maintenance/RuleAvailabilityTask.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/order.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/rules.yml

[Maintenance] refactor to use new maintenance task from pimcore 5.8

---

src/CoreShop/Bundle/FrontendBundle/Controller/WishlistController.php
src/CoreShop/Component/StorageList/Model/StorageListItem.php

[FrontendBundle] fix wishlist remove and allow purchasables

---

src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitions.orm.yml
src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php

Do not lazy load `defaultUnitDefinition` and `unitDefinitions`  in `ProductUnitDefinitions`. Otherwise the pimcore version preview will throw an exception.

always load product unit definitions

---

src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/CarrierType.php

This PR adds `show_carrier_price` and `show_carrier_price_with_tax` form options to `CarrierType`.

add more carrier price options

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20171209154519.php
src/CoreShop/Component/Product/Model/Product.php

[Product] remove getIsAvailableWhenOutOfStock and setIsAvailableWhenOutOfStock

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190617082805.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStoreValues.orm.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/QuantityRange.orm.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/doctrine/model/ProductUnitDefinitionPrice.orm.yml

Follow-Up for #1030. Use BIGINT type to allow crazy deep fraction digits.

change db type for pricing fields to BIGINT

---

src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js

In some cases coreshop.helper might be missing, so this PR fixes this issue.
In some cases coreshop.helper might be missing, so this PR fixes this issue.

Fix missing coreshop.helper namespace

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php
src/CoreShop/Bundle/CurrencyBundle/CoreExtension/MoneyCurrency.php
src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SerializedData.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Multiselect.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php

[CoreExtensions] don't allow any diff until properly implemented

---

src/CoreShop/Bundle/MoneyBundle/DependencyInjection/CoreShopMoneyExtension.php

in case currency-bundle is not installed.

[MoneyBundle] add fallback in money-bundle for decimal precision

---

src/CoreShop/Component/Core/Model/ProductStoreValues.php
src/CoreShop/Component/Core/Model/QuantityRange.php
src/CoreShop/Component/Product/Model/ProductUnitDefinitionPrice.php

[Doctrine] doctrine casts bigint to string, so we have to cast it to int

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/iterator.js

[IndexBundle] fix index iterator interpreter

---

src/CoreShop/Bundle/PimcoreBundle/CoreExtension/EmbeddedClass.php

Protected members are available only via getters.

---

src/CoreShop/Bundle/IndexBundle/Controller/FilterController.php
src/CoreShop/Bundle/IndexBundle/CoreShopIndexBundle.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterConditionTypesPass.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterPreConditionTypesPass.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterUserConditionTypesPass.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/CoreShopIndexExtension.php
src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterPreConditionNestedType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/Filter/FilterUserConditionNestedType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterConditionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterPreConditionChoiceType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterPreConditionCollectionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterPreConditionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterUserConditionChoiceType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterUserConditionCollectionType.php
src/CoreShop/Bundle/IndexBundle/Form/Type/FilterUserConditionType.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/form.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/item.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/filter/panel.js
src/CoreShop/Component/Index/Filter/FilterPreConditionProcessorInterface.php
src/CoreShop/Component/Index/Filter/FilterProcessor.php
src/CoreShop/Component/Index/Filter/FilterUserConditionProcessorInterface.php

[IndexBundle] split conditions into pre_conditions and user_conditions

---

src/CoreShop/Bundle/AddressBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ConfigurationBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/CoreBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/CurrencyBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/CustomerBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/FixtureBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/IndexBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/InventoryBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/MoneyBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/NotificationBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/PaymentBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/PayumBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ProductBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/RuleBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/SequenceBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ShippingBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/StoreBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/TaxationBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/TrackingBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/WorkflowBundle/DependencyInjection/Configuration.php

Corrected the config tree's root node name in order to make configuration available to app
Fixed configuration root key. Currently it is not possible to configure the frontend-bundle without this fix.

Fixing FrontendBundle Configuration

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/reports.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/condition_renderer.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/order_renderer.yml
src/CoreShop/Bundle/MenuBundle/Resources/config/services.yml
src/CoreShop/Bundle/NotificationBundle/Resources/config/services.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/cart-price-rules.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/purchasable.yml
src/CoreShop/Bundle/PimcoreBundle/CoreShopPimcoreBundle.php
src/CoreShop/Bundle/PimcoreBundle/DependencyInjection/Compiler/RegisterTypeHintRegistriesPass.php
src/CoreShop/Bundle/PimcoreBundle/Resources/config/pimcore/routing.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/dynamic_dropdown.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/grid.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services/pimcore.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/price-rules.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/rules.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services/specific-price-rules.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/actions.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/calculator.yml
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/Resources/config/services/product-quantity-price-rules.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/services/installer.yml
src/CoreShop/Bundle/RuleBundle/Resources/config/services/rule_active_validator.yml
src/CoreShop/Bundle/SEOBundle/Resources/config/services.yml
src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml
src/CoreShop/Bundle/ShippingBundle/Resources/config/services/shipping-rules.yml
src/CoreShop/Bundle/ThemeBundle/Resources/config/services.yml
src/CoreShop/Bundle/TrackingBundle/Resources/config/services.yml

Allows:
```php
<?php
namespace AppBundle\Controller;
use CoreShop\Component\Registry\ServiceRegistryInterface;
use Pimcore\Controller\FrontendController;
use Symfony\Component\HttpFoundation\Request;
class DefaultController extends FrontendController
{
public function defaultAction(ServiceRegistryInterface $indexInterpretersRegistry)
{
var_dump($indexInterpretersRegistry->all());exit;
 }
}
```

[AutoWire] improvement: allow service registries to be autowired 

---

src/CoreShop/Bundle/OrderBundle/Form/Type/CartItemType.php
src/CoreShop/Bundle/OrderBundle/Resources/config/validation/CartItem.yml

the Range Validator can't handle that, so now we use the NotEqualTo Validator instead

[OrderBundle] CartItem Quantity has to be > 0

---

src/CoreShop/Bundle/OrderBundle/Controller/CartEditController.php
src/CoreShop/Bundle/OrderBundle/DTO/AddMultipleToCart.php
src/CoreShop/Bundle/OrderBundle/DTO/AddMultipleToCartInterface.php
src/CoreShop/Bundle/OrderBundle/Factory/AddMultipleToCartFactory.php
src/CoreShop/Bundle/OrderBundle/Factory/AddMultipleToCartFactoryInterface.php
src/CoreShop/Bundle/OrderBundle/Form/Type/AddMultipleToCartType.php
src/CoreShop/Bundle/OrderBundle/Form/Type/AddToCartType.php
src/CoreShop/Bundle/OrderBundle/Resources/config/services.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services/forms.yml

[OrderBundle] properly implement AddMultipleToCart

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190226122625.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190308132925.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20190430153230.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20191113105705.php

This PR fix some migration erros:
Use permission category only if available
Remove `coreshop_product_store_values` CONSTRAINT => table is not available yet
Insert `coreshop_product_store_values`CONSTRAINT => table is available

fix some migrations

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20191113121206.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/ProductStoreValues.orm.yml

| Bug fix?      | sort of
After a store gets removed, all values in `coreshop_product_store_values` remain as orphans. This PR changes the coreshop_store constraint from `SET NULL` to `CASCADE`.

Remove Store Values after Store has been removed

---

src/CoreShop/Component/Order/Generator/CartPriceRuleVoucherCodeGenerator.php

`33` is a defined length for `FORMAT_ALPHANUMERIC` - if you're using `FORMAT_ALPHABETIC` or `FORMAT_NUMERIC` only, it will return null values which generates codes with wrong lengths.

Fix Character Length Count in Voucher Code Generator

---

src/CoreShop/Component/Pimcore/DataObject/ObjectService.php

There's no need to assert the object type because it is defined for the parameters anyways.
Apart from that, the `webmozart/assert` library is not required in composer for this component.

Remove unnecessary type assertions in `Pimcore` component

---

docs/03_Development/08_Index_and_Filters/01_Index/README.md
src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php

This PR adds an argument to the coreshop:index command, which allows defining certain index IDs to re-index. Default stays the same: all indices get re-indexed.
Additionally, if no indices are found (either by ID lookup or findAll method) a message is displayed in the console.

Argument for re-index command

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20200107065213.php

+ add missing ContainerAwareInterface
| Fixed tickets | #1209 
| Affected PRs | #1217 #1222 
Added missing ContainerAwareInterface in migration.
Fixes `getParameter() on null` error during migration.

GH-1209 fix migration

---

src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php

Branch: 2.0
Use single item price (`getItemPrice`) instead of item price * quantity (`getTotal`).

[TRACKING] use single item price in order item extractor

---

src/CoreShop/Component/Core/Tracking/Extractor/OrderItemExtractor.php

Branch: 2.1
Use single item price (`getItemPrice`) instead of item price * quantity (`getTotal`).

[TRACKING] use single item price in order item extractor in CS 2.1

---

src/CoreShop/Bundle/CoreBundle/Controller/ProductValidationController.php

The validation controller for product unit definitions only worked for the default product model and not with multiple. Now it can query all product models via the stack repository.

[CoreBundle] Change repository so that unit definition deletion works with multiple product models 

---

docs/03_Development/01_Extending_Guide/04_Extending_Rule_Actions.md
docs/03_Development/01_Extending_Guide/05_Extending_Rule_Conditions.md

I changed the `bin/console assets:install` to `bin/console assets:install web`, because Symfony will using `public` by default in current versions. I also copied the hint from *Extending Rule Action* to *Extending Rule Condition*

change assets:install for fresh installations

---

features/recycle_bin/store_values.feature
src/CoreShop/Behat/Context/Domain/RecycleBinContext.php
src/CoreShop/Behat/Context/Setup/RecycleBinContext.php
src/CoreShop/Behat/Resources/config/services/contexts/domain.yml
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Behat/Resources/config/suites.yml
src/CoreShop/Behat/Resources/config/suites/domain/recycle_bin.yml
src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ResourceBundle/CoreExtension/Select.php
src/CoreShop/Component/Pimcore/BCLayer/CustomRecyclingMarshalInterface.php

caused by https://github.com/pimcore/pimcore/pull/5507 and sort of fixed with https://github.com/pimcore/pimcore/pull/5588

[CoreExtensions] fix issue with CoreShop CoreExtensions Recycle Bin

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/item.js

[IndexBundle] index ui improvements

---

src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

for `coreshop.ui.search_results_for`

fix: add missing translation

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20190605141526.php
src/CoreShop/Bundle/CoreBundle/Migrations/Version20200224164328.php
src/CoreShop/Bundle/CoreBundle/Resources/config/doctrine/model/Payment.orm.yml
src/CoreShop/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.yml
src/CoreShop/Bundle/PaymentBundle/composer.json
src/CoreShop/Bundle/PayumBundle/Action/AuthorizePaymentAction.php
src/CoreShop/Bundle/PayumBundle/Action/CapturePaymentAction.php
src/CoreShop/Bundle/PayumBundle/Action/ExecuteSameRequestWithPaymentDetailsAction.php
src/CoreShop/Bundle/PayumBundle/Resources/config/services.yml
src/CoreShop/Component/Core/Model/Payment.php
src/CoreShop/Component/Core/Model/PaymentInterface.php
src/CoreShop/Component/Order/Model/OrderPaymentInterface.php
src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php
src/CoreShop/Component/Payment/Model/Payment.php
src/CoreShop/Component/Payment/Model/PaymentInterface.php
src/CoreShop/Component/Payment/composer.json

[Payment] decouple Payment from Payum and consider decimal factor

---

UPGRADE-3.0.x.md
src/CoreShop/Behat/Context/Domain/FilterContext.php
src/CoreShop/Behat/Model/Index/TestEnableIndex.php
src/CoreShop/Behat/Model/Index/TestIndex.php
src/CoreShop/Behat/Model/Index/TestIndexFields.php
src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php
src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Index/Model/IndexableInterface.php

[3.0] change IndexableInterface and pass IndexInterface

---

src/CoreShop/Bundle/FrontendBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Expiration/OrderExpiration.php

| New feature?  | sort of?
| Fixed tickets | #1319

[Order] persist internal cancellation reasons

---

src/CoreShop/Bundle/PimcoreBundle/Controller/Admin/DynamicDropdownController.php

This PR fixes sanitizing the parent folder path when trying to load the options for dynamic dropdown tags. It uses the same validation as Pimcore. Furthermore, the method now returns an empty array, if the folder could not be found.

[Pimcore Bundle] Fix loading dynamic dropdown options

---

src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/SuperBoxSelect.php

[PimcoreBundle] fix dynamic dropdown extensions

---

src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdown.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/DynamicDropdownMultiple.php
src/CoreShop/Bundle/PimcoreBundle/CoreExtension/ItemSelector.php

[DynamicDropdown] add dependency resolving

---

src/CoreShop/Bundle/ThemeBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php
src/CoreShop/Bundle/ThemeBundle/Exception/CircularDependencyFoundException.php
src/CoreShop/Bundle/ThemeBundle/Service/InheritanceLocator.php

Allows to have theme inheritance and re-use themes in other themes:
```yml
core_shop_theme:
inheritance:
agro_at:
- agro_de
agro_com:
- agro_at
```

[ThemeBundle] introduce theme inheritance

---

src/CoreShop/Bundle/ResourceBundle/Validator/Constraints/UniqueEntityValidator.php

Not working because it checked the object against the object id

[ResourceBundle] Fix unique entity validator

---

src/CoreShop/Bundle/WorkflowBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/WorkflowBundle/EventListener/WorkflowListener.php

Easily disable any callback defined on workflows. useful if you want to disable callbacks, when customizing existing workflows of CoreShop or disable callbacks based on parameters.

[WorkflowBundle] Add enabled option to workflow callbacks

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services/taxation.yml
src/CoreShop/Bundle/CoreBundle/Twig/ProductTaxExtension.php
src/CoreShop/Bundle/CoreBundle/Twig/TaxationDisplayProviderExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/Macro/product_price.html.twig
src/CoreShop/Component/Core/Taxation/DefaultTaxationDisplayProvider.php
src/CoreShop/Component/Core/Taxation/TaxationDisplayProviderInterface.php

[3.0] introduce tax-display service

---

src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php

Fixed issue with saving address changes, reproducible on [demo](https://demo2.coreshop.org):
Issue is caused by `CustomerTransformHelper` responsible for saving address, but saving is done only in case the address is new or parent is different.
https://github.com/coreshop/CoreShop/blob/9228f1a6d346deb934387c32c033dd5c172d791f/src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php#L175-L178

Fixed issue with saving address changes

---

src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php
src/CoreShop/Component/ProductQuantityPriceRules/Model/ProductQuantityPriceRule.php
src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRange.php

Without resetting the id, entities won't get cloned. Instead the master entity data will just get moved.

re-add id reset on entity clone

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/order/detail/blocks/carriage.js
src/CoreShop/Bundle/CurrencyBundle/Resources/config/serializer/Model.Currency.yml
src/CoreShop/Bundle/OrderBundle/Controller/AbstractCartCreationController.php
src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleDetailController.php
src/CoreShop/Bundle/OrderBundle/Controller/CartController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/cart/detail/blocks/detail.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/detail/blocks/payment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editInvoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/invoice.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/shipment.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/products.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/create/step/totals.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/detail.js
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/detail/blocks/header.js
src/CoreShop/Bundle/ShippingBundle/Resources/config/services.yml

The sale detail views are not working when using JMS Serializer because the currency is formatted in the wrong structure. This PR fixes that problem by changing the property access to `sale.currency.isoCode` instead of `sale.currency.iso`

[OrderBundle][CoreBundle] Fix currency formatting in sale detail related components

---

src/CoreShop/Bundle/OrderBundle/Form/Type/Rule/Condition/AmountConfigurationType.php

There is a check if a value is 0 in the condition checker, but 0s are not valid in the given form configuration

[OrderBundle] Values should be zero, if amount should not be defined

---

src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php

Backport of https://github.com/coreshop/CoreShop/pull/1434

[2.2][FrontendBundle] apply confirm and pay transition for orders with value of 0

---

src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/sale/list.js

[OrderBundle] don't remove certain elements from toolbar, just hide them

---

src/CoreShop/Component/Store/Context/RequestBased/CompositeRequestResolver.php
src/CoreShop/Component/Store/Context/RequestBased/PimcoreAdminSiteBasedRequestResolver.php
src/CoreShop/Component/Store/Context/RequestBased/RequestResolverInterface.php
src/CoreShop/Component/Store/Context/RequestBased/SiteBasedRequestResolver.php

| Fixed tickets | #1463 
Changed type hint of the findStore method to allow null values. This method returns null for sites that are not connected to any store. 
BC breaks because we change the return type of a method in RequestResolverInterface.

Allow null return value in request resolver find store

---

src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/specificprice/object/item.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/helpers.js
src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/resource/item.js

[ProductBundle] fix persistance of spefiic-product-price-rule label

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

otherrwise we don't know if belongs to the object or not

[CoreBundle] don't set product for store-values on pre-get-data

---

src/CoreShop/Component/Pimcore/BatchProcessing/BatchListing.php
src/CoreShop/Component/Pimcore/BatchProcessing/DataObjectBatchListing.php

the current batch list has the problem that it doesn't work when you delete objects during the run, this new list only works for DataObjects and resolves that issue
| Bug fix?      | yes and no

[Pimcore] introduce DataObjectBatchListing

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php

open order detail failed because some parameters not a string, a fixed preview:

fix payment details in backed order view

---

src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php

Fix for:
Error: ini_set() expects parameter 2 to be string, bool given (500 Internal Server Error)
File: vendor/coreshop/core-shop/src/CoreShop/Bundle/OrderBundle/Controller/CartPriceRuleController.php::164

fix voucher code export

---

src/CoreShop/Bundle/ResourceBundle/EventListener/DeepCopySubscriber.php
src/CoreShop/Bundle/ResourceBundle/Resources/config/services.yml

Credits for this go to @ramundomario

[ResourceBundle] add Pimcore DeepCopy Subscriber to fix doctrine collections clone problem

---

src/CoreShop/Bundle/CoreBundle/Form/Type/AddressChoiceType.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/form.yml

When a customer only has access to company addresses, checkout is not possible as those addresses not show up.
This can be fixed by using the already implemented CustomerAddressAllocator also for FormType AddressChoiceType
Q | A
-- | --
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Fixed tickets |  
This pull request fixes a problem when a customer wants to do a checkout but only has access to the company addresses. The addressAccessType was not considered till now in CoreShop\Bundle\CoreBundle\Form\Type\AddressChoiceType.

Fix checkout with addressAccessType COMPANY_ONLY

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderPaymentController.php

It's not possible to add a new payment in backend if a failed payment is available.

ignore failed payments in total amount check

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/address.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Customer/addresses.html.twig
src/CoreShop/Component/Core/Customer/Address/AddressAssignmentManager.php

- `getAddressAccessType` can be null or an empty string (pimcore at its best...)
- Add address type badge to address overview card for better identification (if defined)
- Add address type headline on editing for better identification (if defined)

fix addressAccessType check and improve view

---

docs/02_Components/Product_Unit.md

| Fixed tickets | no
| Documentation | yes
Add documentation for using product units in php. Just not sure, whether this is the right spot in the documentation tree and also if the code is correct.
More a proposal.

add docu for product units

---

src/CoreShop/Bundle/ProductBundle/Form/Type/Unit/ProductUnitDefinitionsChoiceType.php

Use fully translated label instead of generic unit definition name:

use full unit definition label in choice field

---

src/CoreShop/Component/Core/Shipping/Calculator/TaxedCarrierPriceRuleCalculator.php
src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyCartItems.php
src/CoreShop/Component/Core/Shipping/Taxation/TaxCalculationStrategyTaxRule.php
src/CoreShop/Component/Shipping/Checker/CarrierShippingRuleChecker.php
src/CoreShop/Component/Shipping/Model/ShippableItemInterface.php

[Shipping] make shipping calculation more independent from cart

---

composer.json
src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/AddressIdentifierRepository.php
src/CoreShop/Bundle/AddressBundle/Doctrine/ORM/CountryRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/CarrierRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ConfigurationRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/CountryRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/CurrencyRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/TaxRuleRepository.php
src/CoreShop/Bundle/CurrencyBundle/Doctrine/ORM/CurrencyRepository.php
src/CoreShop/Bundle/CurrencyBundle/Doctrine/ORM/ExchangeRateRepository.php
src/CoreShop/Bundle/PaymentBundle/Doctrine/ORM/PaymentProviderRepository.php
src/CoreShop/Bundle/ProductBundle/Doctrine/ORM/ProductUnitDefinitionsRepository.php
src/CoreShop/Bundle/ProductBundle/Doctrine/ORM/ProductUnitRepository.php
src/CoreShop/Bundle/ResourceBundle/CoreShopResourceBundle.php
src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/StoreBundle/Doctrine/ORM/StoreRepository.php
src/CoreShop/Bundle/TaxationBundle/Doctrine/ORM/TaxRateRepository.php
src/CoreShop/Component/Registry/PriorityMap.php

Cache causes some weird behaviours, therefore we have to remove it in a patch release, but if you actually need it, you can just add what we removed here.

[DoctrineCache] remove doctrine cache and all usages of useQueryCache and useResultCache

---

src/CoreShop/Component/Index/Filter/RangeFilterConditionProcessor.php

[IndexBundle] Fix range filter to work if min/max value = 0

---

src/CoreShop/Component/ProductQuantityPriceRules/Fetcher/QuantityPriceFetcherInterface.php
src/CoreShop/Component/ProductQuantityPriceRules/Fetcher/QuantityRuleFetcher.php
src/CoreShop/Component/ProductQuantityPriceRules/Fetcher/QuantityRuleFetcherInterface.php

[ProductQuantityPriceRules] add interface for QuantityPriceFetcher and QuantityRuleFetcher

---

config/packages/security.yaml
src/CoreShop/Bundle/CoreBundle/Resources/config/pimcore/security.yml

When the core shop is accessible directly under URL path `/` (so like when you call the home page https://example.org/) the logged in customer cannot be found with the `TokenBasedRequestResolver` because path `/` does not match the regex `^/(?!admin)[^/]++`.

Fix Firewall for URL path /

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary/_rules.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/order_detail.html.twig
src/CoreShop/Bundle/FrontendBundle/Resources/views/Quote/show.html.twig

Print cart price rule label instead name, if available, in all places

[FrontendBundle] Print cart price rule label instead name if available

---

src/CoreShop/Bundle/ResourceBundle/Pimcore/ObjectManager.php

When creating an object the $id was overwritten in the getResourceId method and set to null. This created a php exception and breaks the code.
This code change will prevent that by checking if the id of the resource object is not null.

Prevent PHP exception by non nullable return type

---

src/CoreShop/Bundle/NotificationBundle/Controller/NotificationRuleController.php

getParametetr needs to be called via container

Bugfix for getParameter call

---

src/CoreShop/Bundle/MoneyBundle/CoreExtension/Money.php

When saving a DataObject containing a money field, it errors out on saving, because the number typed in into the field is parsed as a string to the PHP function. That is easily mitigated by parsing the string into a float, because the function already checks if the string is numeric.
| Fixed tickets | none
[This](https://prnt.sc/1sa6csc) happens normally when trying to save a DataObject containing a CoreShop money field.

fix: Error on saving money field

---

src/CoreShop/Component/Pimcore/BatchProcessing/BatchListing.php
src/CoreShop/Component/Pimcore/BatchProcessing/DataObjectBatchListing.php

I would expect `key()` to return a consecutive number, but that is not currently the case.
Suppose `$batchSize` is `3`. Then `key()` would return the following in the current implementation: 1, 2, 3, 2, 4, 6, 3, 6, 9, ...
So the first batch would have the expected keys. The following ones, however, would not, since `$this->loop` is incremented and `$this->index` is reset with each batch. 
Thus, the current code `($this->index + 1) * ($this->loop + 1)` results in:
```
(0 + 1) * (0 + 1) = 1
(1 + 1) * (0 + 1) = 2
(2 + 1) * (0 + 1) = 3
(0 + 1) * (1 + 1) = 2
(1 + 1) * (1 + 1) = 4
(2 + 1) * (1 + 1) = 6
(0 + 1) * (2 + 1) = 3
(1 + 1) * (2 + 1) = 6 …
```

Fix `(DataObject)BatchListing::key()`

---

src/CoreShop/Bundle/StoreBundle/CoreExtension/Store.php
src/CoreShop/Bundle/StoreBundle/CoreExtension/StoreMultiselect.php
src/CoreShop/Bundle/StoreBundle/CoreExtension/StoreOptionProvider.php
src/CoreShop/Bundle/StoreBundle/Resources/config/services.yml

Currently it is not possible to fetch the available options for store select / multiselect field types as you would normally do for Pimcore default select / multiselect fields via 
```php
$object->getClass()->getFieldDefinition('store')->getOptions(); // returns always null
DataObject\Service::getOptionsForSelectField($object, "store"); // also returns always null
```
This is currently always `null` as the logic for fetching the available options is only implemented in JS, see https://github.com/coreshop/CoreShop/blob/99bbb0c927d2cc57ca81bd3b03dbd5805a6172c8/src/CoreShop/Bundle/StoreBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopStoreMultiselect.js#L …

[Store select / multiselect] Support getOptions() via option provider

---

src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/CoreShopResourceExtension.php

| New feature?  | yes/
Allows you to define custom resources without the need of a DI Extension like:
**Pimcore Models**
```
core_shop_resource:
pimcore:
app.test:
path:
test: test
classes:
model: Pimcore\Model\DataObject\Test
interface: App\Model\TestInterface
```
**Doctrine Entities** 
```
core_shop_resource:
resource:
app.doctrine_test:
classes:
model: App\Entity\DoctrineTest
interface: App\Model\DoctrineTestInterface
repository: CoreShop\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
```
You than have access to services like factory or repository like:
```
$container->get('app.repository.test');
$container->get('app.repository.doctrine_test'); …
```

[ResourceBundle] allow easier custom resources

---

src/CoreShop/Bundle/IndexBundle/ProcessManager/IndexProcess.php

Currently it throws an exception that the method signature is incompatible.

fix: make IndexProcess compatible with the interface

---

src/CoreShop/Bundle/CoreBundle/Form/Extension/PaymentProviderTypeExtension.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/form_extension.yml

[CoreBundle] fix saving stores in PaymentProvider

---

src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/CartRepository.php
src/CoreShop/Component/Order/Repository/CartRepositoryInterface.php

specially on findLatestByStoreAndCustomer it can happen that more then one cart exists for the customer, when the user has logged in, he has been shown an empty cart. although several carts exist, the last cart should be loaded.

[Cart] fix existing cart initalization on customer login

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/product.yml
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinition.php
src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Component/Core/Model/ProductInterface.php
src/CoreShop/Component/Core/Model/ProductStoreValues.php
src/CoreShop/Component/Core/Model/QuantityRange.php
src/CoreShop/Component/Core/Product/Cloner/ProductQuantityPriceRulesCloner.php
src/CoreShop/Component/Core/Product/Cloner/ProductUnitDefinitionsCloner.php
src/CoreShop/Component/Core/Product/Cloner/UnitMatcher.php
src/CoreShop/Component/Core/Product/Cloner/UnitMatcherInterface.php
src/CoreShop/Component/Pimcore/BCLayer/CustomDataCopyInterface.php
src/CoreShop/Component/Product/Model/ProductSpecificPriceRule.php
src/CoreShop/Component/Product/Model/ProductUnitDefinition.php
src/CoreShop/Component/Product/Model/ProductUnitDefinitions.php
src/CoreShop/Component/ProductQuantityPriceRules/Model/ProductQuantityPriceRule.php
src/CoreShop/Component/ProductQuantityPriceRules/Model/QuantityRange.php
src/CoreShop/Component/Resource/Pimcore/Model/PimcoreModelInterface.php
src/CoreShop/Component/Rule/Model/Condition.php

| Fixed tickets | #1765
Don't use `__clone` anymore, as it is way too unpredictable in some matters. Use a `CustomCopy` from Pimcore and manually clone and reset data. This also doesn't completely clone all the data, since we have some dependencies from store-values to Product Unit Definitions. But this is something we cannot solve this way and therefore is simply just not supported. This also fixes copying of Specific Product Price Rules and Quantity Price Rules.
<!-

[CoreExtensions] refactor how Doctrine Entities are cloned

---

src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/CartRepository.php
src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php

| Fixed tickets | #1699 (partial)

fixes #1699 cart context returns latest cart even if multiple found

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php

Followup https://github.com/coreshop/CoreShop/pull/1807#issuecomment-989913502
It should fix the Behat UI failed test of #1812
Instead of taking the value from request we could get the value from the extra data of the form, let me know WDYT @dpfaffenbauer

[CoreBundle] Fix fetch of `checkout_finisher` url from request

---

src/CoreShop/Bundle/IndexBundle/EventListener/AdminJavascriptListener.php

| Fixed tickets | #1809 
This change fixes the generation of the wrong menu route (`coreshop.index` instead of `coreshop.main`).

fix: generate the correct menu route

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/SummaryType.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig

Followup https://github.com/coreshop/CoreShop/pull/1814#issuecomment-990802721
With this change submit order & submit quote urls are generated in `getResponse()` function of `SummaryCheckoutStep` instead of value of submit buttons

[CoreBundle] Add submit buttons in SummaryType and generate urls in SummaryCheckoutStep

---

src/CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/SummaryType.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml
src/CoreShop/Bundle/FrontendBundle/Resources/views/Checkout/steps/summary.html.twig
src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php
src/CoreShop/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php
src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php
src/CoreShop/Component/Resource/Pimcore/Model/PimcoreModelInterface.php

| Fixed tickets | https://github.com/coreshop/CoreShop/issues/1746
Add a check if the parent exists. Tested in /de/shop/customer/addresses and also in the checkout process.

Add address parent check

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20220117153741.php

I think this should be `json` instead of `json_array`, too.

Fix doctrine type in migration (followup of #1839)

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CoreShopFrontendExtension.php
src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml

Valid category sort options are hardcoded in CategoryController. This PR makes them configurable via parameters.

Make category sort options configurable

---

src/CoreShop/Bundle/CustomerBundle/Form/Type/ResetPasswordType.php
src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/translations.yml

Currently there is a bit of a UX problem when resetting the password. We had some customers who wondered why they have to type their password when they actually want to reset it. To make it clearer that with the password-reset form it is actually possible to change to a **new** password, this PR changes the field labels.

Password reset: Clearer form labels

---

src/CoreShop/Bundle/IndexBundle/Resources/config/services/listeners.yml

| Fixed tickets | #1865
Fix for #1865

[CoreShopIndexBundle] Add `pimcore.dataobject.postAdd` event to index DataObjects

---

src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php
src/CoreShop/Bundle/CoreBundle/Form/Type/Notification/Condition/OrderSaleStateConfigurationType.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/notification.yml
src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/notification/conditions/order/saleState.js

[CoreBundle] fix quote notification sending 3.x

---

src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php
src/CoreShop/Component/Pimcore/BCLayer/EqualComparisonInterface.php

This PR implements the `isEqual()` method for product-specific price rules.

Add isEqual() for product-specific price rules

---

src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js

You can double click field groups and add them to indexed fields.

FIX:double click on field group adds them to indices

---

psalm.xml
src/CoreShop/Bundle/IndexBundle/Controller/IndexController.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js
src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/interpreters/nested.js
src/CoreShop/Component/Index/Getter/BrickGetter.php
src/CoreShop/Component/Index/Getter/FieldCollectionGetter.php
src/CoreShop/Component/Index/Getter/LocalizedFieldGetter.php
src/CoreShop/Component/Index/Interpreter/LocalizedNestedInterpreter.php
src/CoreShop/Component/Pimcore/DataObject/LocaleFallbackHelper.php

Brick and fieldcollections with localazied fields are now indexable.

FIX: localized fields from brick and fieldcollections can be added to index

---

src/CoreShop/Bundle/PaymentBundle/Resources/config/services/pimcore.yml

coreshop_payment_provider editable was using property Named 'name' instead of the 'title'.

FIX: coreshop_payment_provider editable select, wrong property name

---

src/CoreShop/Bundle/ResourceBundle/CoreExtension/CoreShopRelation.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php

The stack for `coreshop.manufacturer` and `coreshop.address` was not working, because the classes have not been extended in the CoreBundle. Therefore I adjusted the check in the StackClassesPass to also work with not extended classes.

[ResourceBundle] Make stack of classes not extended in CoreBundle working

---

src/CoreShop/Component/Index/Filter/SelectFilterConditionFromMultiselectProcessor.php

If you create select from multiselect filter and don't preselect the value exception is thorwn. trim(): Argument #1 ($string) must be of type string, null given.

FIX: select from multiselect throws error if no value is pre-selected

---

src/CoreShop/Bundle/UserBundle/Form/Type/RequestResetPasswordType.php

Currently you can submit blank value for email on request password reset form and  submitting blank value causes exception.

Email field required on request reset password form

---

src/CoreShop/Bundle/IndexBundle/DependencyInjection/Compiler/RegisterFilterConditionTypesPass.php

Extending filter condition processor adds empty tag to definition. It probably isn't imagined to be extended but it should cover that case also.

FIX: extending condition proccesor adds empty tag

---

src/CoreShop/Bundle/OrderBundle/Resources/config/serializer/Model.OrderInvoice.yml

| New feature? | no
During serialization of orderInvoice error appears because serializer can't find property getItems on orderInvoice, getItems is a method

Error during serialization of OrderInvoice

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/_header.html.twig

Logo path shouldn't be hardcoded here.

fix: logo in _header.html.twig no longer hardcoded

---

src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js

| Fixed tickets | #
Unit Definition collapsible title is no longer duplicated.

FIX: duplicated unit definition title in product view in admin

---

src/CoreShop/Bundle/OrderBundle/Renderer/Pdf/WkHtmlToPdf.php

The comment in code suggests that XVFB is optional, so getter for XVFB shouldn't throw exception.
`
// use xvfb if possible
`
Also process needs to be created in a different way.

Fix xvfb error

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/paginator.html.twig

fix: paginator prev/next links point to first/last page

---

.github/workflows/behat.yml
.gitignore
composer.json
src/CoreShop/Bundle/CoreBundle/DependencyInjection/Compiler/RegisterIndexProductExtensionPass.php
src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php
src/CoreShop/Bundle/IndexBundle/Controller/IndexController.php
src/CoreShop/Bundle/NotificationBundle/Controller/NotificationRuleController.php
src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php
src/CoreShop/Bundle/ResourceBundle/Controller/ResourceSettingsController.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterPimcoreResourcesPass.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/RegisterResourcesPass.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackClassesPass.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Compiler/StackRepositoryPass.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Driver/Pimcore/PimcoreDriver.php
src/CoreShop/Bundle/ResourceBundle/DependencyInjection/Extension/AbstractModelExtension.php
src/CoreShop/Bundle/ResourceBundle/Installer/AbstractTranslationInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreDocumentsInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreGridConfigInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreImageThumbnailsInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcorePermissionInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreRoutesInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/SqlInstaller.php
src/CoreShop/Bundle/ShippingBundle/Controller/CarrierController.php

[Stan] fix tests

---

src/CoreShop/Bundle/CoreBundle/Collector/CurrencyCollector.php

In case there is no store defined inside constructor code will enter catch part and $this->data will never be set, so the method getCurrency will throw and error and profile wont work

Profiler fix

---

src/CoreShop/Bundle/FrontendBundle/Resources/views/Common/paginator.html.twig

URLs generated by the paginator by default have 4 spaces prepended to them, like
```html
<a href="    /category?page=2">2</a>
```
This removes the spaces.

fix: paginator.html.twig prepends four spaces to URLs

---

src/CoreShop/Bundle/CoreBundle/Customer/CustomerManager.php

When the customer that should be persisted in `CustomerManager::persistCustomer()` has no addessses yet, the property may be `null`, which fails when trying to iterate over it. We should fall back to an empty array in this case.

Handle `null` addresses when persisting customers

---

src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/grid-config.yml

Default grid configs for order views are broken because they are using Href relation type

Fix for order grid configs

---

src/CoreShop/Bundle/CoreBundle/Form/Type/Checkout/CarrierChoiceType.php
src/CoreShop/Bundle/CoreBundle/Resources/config/services/checkout.yml

[CoreBundle] use TaxationDisplayProvider in CarrierChoiceType

---

src/CoreShop/Bundle/CoreBundle/Pimcore/Repository/CategoryRepository.php

The `findForStore()` and `findFirstLevelForStore()` (see #1914) are used for menus. It makes sense to default to the `o_index` sort which allows customizing the order of items in the menu. If not desired, it can be reset to the A-Z sort by Pimcore.

feat: use the index for categories to allow fine tuning the menus

---

src/CoreShop/Component/Pimcore/ExpressionLanguage/PHPFunctionsProvider.php

These functions are a common requirement if your expressions deal with paths.

feat: add dirname() and basename() to expression function provider

---

src/CoreShop/Component/Core/Model/Product.php
src/CoreShop/Component/Index/Model/IndexableInterface.php

This change allows the "getIndexableName()" method to return null, e.g. multiple languages, which have not been filled in yet.

[Product Model] Allow `getIndexableName()` to return null

---

src/CoreShop/Bundle/FrontendBundle/DependencyInjection/CompilerPass/RegisterFrontendControllerPass.php

[Frontend] fix controller overwriting

---

src/CoreShop/Bundle/TrackingBundle/Resources/views/Tracking/gtm/enhanced/checkout.js.twig
src/CoreShop/Bundle/TrackingBundle/Resources/views/Tracking/gtm/enhanced/checkout_complete.js.twig
src/CoreShop/Bundle/TrackingBundle/Resources/views/Tracking/gtm/enhanced/product_impression.js.twig
src/CoreShop/Bundle/TrackingBundle/Resources/views/Tracking/gtm/enhanced/product_view.js.twig
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/TagManager/TagManagerEnhancedEcommerce.php

fixing some of the listed issues in the ticket
Fixed:
- trackCheckoutComplete - Rename total to revenue
- trackProductImpression - remove quantity, brand, position, attribute
- trackCartAdd - quantity is hardcoded to 1. Use $quantity instead
Template issues
- product_impression.js.twig
- product_view.js.twig
- checkout.js.twig
- checkout_complete.js.twig
Not fixed:
- trackProductImpression - submit impression as multi- instead of single-array
- trackCartAdd - price attribute: I'm not sure about that but I think we need to use the cart item price instead of product price (which often can't be determinate (because of complex variant structure etc.)
- trackCartRemove …

#1613 TagManagerEnhancedEcommerce

---

src/CoreShop/Bundle/TrackingBundle/Resolver/ConfigResolver.php
src/CoreShop/Bundle/TrackingBundle/Tracker/Google/GlobalSiteTagEnhancedEcommerce.php

Small tweaks for the GA tracking features.

fix: property must not be accessed before initialization

---

src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartStockAvailabilityValidator.php

| Deprecations? no
`$cartItem->getDefaultUnitQuantity();` could return null here  and cause a TypeError.

[CoreBundle] check for null value in CartStockAvailabilityValidator

---

src/CoreShop/Bundle/VariantBundle/Twig/Extension/VariantExtension.php

With this PR the value of `$innerObject` is allowed to be null when serializing a variant group. This prevents throwing an error when rendering the product detail page and thus makes this process more flexible.

[VariantBundle] Serializer: Allow $innerObject to be null

---

src/CoreShop/Bundle/ProductBundle/Controller/ProductUnitDefinitionsController.php
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/coreExtension/tags/coreShopProductUnitDefinitions.js
src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js

| Fixed tickets | #2040
I'm not 100% sure if this is the correct place to fix the issue of not having an empty entry in the store. @dpfaffenbauer Could you please check and advise if there's a "better way" of adding an empty entry to a CoreShop resource list.
Thanks!

[Pimcore UI] Make default Product Unit unselectable

---

CHANGELOG-3.0.x.md
src/CoreShop/Bundle/CoreBundle/Application/Version.php

🎉  🍻 
This it it, the final release of CoreShop 3.0.0. After more than 2 years of development, we finally made it with a final release to Pimcore X. Took a bit longer than we thought, but good things need time.
Conceptually, the Order, Cart and Quote are the same. They hold the same amount of information, they are calculated the same and work the same. So why differentiate the 3? With CoreShop 3 we now see them as one and use them as one. The way to differentiate between them is with a State. The Workflow State Machine can change the Status from Cart to Order or Quote.
CoreShop never really solved the Variant Selection Problem. Reason was that the concept of Variants can be quite difficult with Pimcore. With CoreShop 3.0 we introduce a simple solution to configure and display Variants in …

[Release] 3.0.0

---

src/CoreShop/Component/Variant/Model/ProductVariantTrait.php

With this PR you no longer receive the following error:
```log
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '344 lt/%' AND  object_localized_cs_product_de_CH.o_type IN ('variant')) AND o...' at line 1 in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:141
Stack trace:
#0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(141): PDO->query()
#1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOQueryImplementation.php(24): Doctrine\DBAL\Driver\PDOConnection->doQuery()
#2 …
```

[ProductVariantTrait] Prevent MySQL syntax error

---

src/CoreShop/Bundle/CoreBundle/Menu/MainMenuBuilder.php

This PR fixes the permission for the product unit menu item configured through user permissions.

[Menu] Use correct permission definition for product unit menu item

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php
src/CoreShop/Bundle/IndexBundle/Worker/MysqlWorker.php

Since pimcore o_classId is string (varchar(50)) and inside index table o_classId is set to int type, values are not saved correctly inside index table

fix: index table o_classId type fix

---

src/CoreShop/Bundle/CoreBundle/Resources/public/pimcore/js/customer/customerToExistingCompanyAssignment.js

Before this PR the following URL is generated:
```log
/admin/coreshop/customer-company-modifier/dispatch-existing-assignment/16685/undefined
```
Which leads to following error:
```log
CoreShop\Bundle\CoreBundle\Controller\CustomerTransformerController::dispatchExistingAssignmentAction():
Argument #3 ($companyId) must be of type int, string given
```
With this PR, the correct company ID gets passed to the router and there generates the correct URL.

[CustomerAssignment] Fix typo when passing the company ID to the router

---

config/packages/test/config.yaml
src/CoreShop/Behat/Context/Setup/PimcoreClassContext.php
src/CoreShop/Behat/Resources/config/services/contexts/setup.yml
src/CoreShop/Bundle/IndexBundle/EventListener/IndexObjectListener.php
src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
src/CoreShop/Bundle/IndexBundle/Messenger/IndexMessage.php
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/config.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/pimcore/messenger.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/listeners.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services/messenger.yml

[IndexBundle] process Index Messages async

---

src/CoreShop/Bundle/ResourceBundle/Command/InstallResourcesCommand.php
src/CoreShop/Bundle/ResourceBundle/Installer/CompositeResourceInstaller.php
src/CoreShop/Bundle/ResourceBundle/Installer/PimcoreClassInstaller.php

Add command option `update-classes` to the `InstallResourcesCommand` (`coreshop:resources:install`) to have the possiblity to update Pimcore class definitions.
When the command is executed, configuration from a bundles dependency injection (`Configuration.php`) is used to read in exported json files and to update the definition files for Pimcore.
In the current process, field definitions and objectbrick definitions are always updated, but class definitions never. So i thought why not have an option for classes as well.

add option 'update-classes' for InstallResourcesCommand

---

src/CoreShop/Bundle/MessengerBundle/Controller/ListMessagesController.php
src/CoreShop/Bundle/MessengerBundle/Exception/ReceiverNotListableException.php
src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRejecter.php
src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRepository.php
src/CoreShop/Bundle/MessengerBundle/Messenger/FailedMessageRetryer.php
src/CoreShop/Bundle/MessengerBundle/Messenger/MessageRepository.php
src/CoreShop/Bundle/MessengerBundle/Messenger/ReceiversRepository.php
src/CoreShop/Bundle/MessengerBundle/Messenger/ReceiversRepositoryInterface.php
src/CoreShop/Bundle/MessengerBundle/Resources/config/pimcore/routing.yml
src/CoreShop/Bundle/MessengerBundle/Resources/public/pimcore/js/list.js

[MessengerBundle] only allow to list ListableReceiverInterface

---

src/CoreShop/Bundle/OrderBundle/Resources/views/OrderDocumentPrint/header.html.twig

fix: use asset() helper for logo image

---

src/CoreShop/Bundle/CoreBundle/Migrations/Version20220817144952.php

When deciding if the new layout `price_rules` and field `priceRuleItems` need to be added to the class definition use the field's name for existence check and not the layout's name. Otherwise its existence is not properly detected which leads to multiple inserts if the migration is called multiple times or the field had already been added otherwise.
| Fixed tickets | #2148

Add layout `price_rules` only once to OrderItem

---

psalm.xml
src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php
src/CoreShop/Bundle/IndexBundle/Resources/config/services/messenger.yml

Improves performance. It is faster to handle children in the same Handler, than to lock the Doctrine Messenger Table

[IndexBundle] process children within same Handler

---

src/CoreShop/Bundle/IndexBundle/Command/IndexCommand.php

Unpublished objects are not available when executing the `coreshop:index` command. In some scenarios, this could lead to some orphans in the index (Error while removing an unpublished object from index will never ever get removed once an exception has been thrown)
Use `coreshop:index -u` to assert all objects are in sync, since it will include unpublished objects!

allow unpublished objects in index command

---

src/CoreShop/Bundle/IndexBundle/Worker/AbstractWorker.php

use correct parent for virtual object active state

---

src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php

When a data object class uses field type `Store Values`, the store may not have a currency set yet.
Steps to reproduce bug:
1. Create product
2. Create new store (it gets created without currency - required field check is only done afterwards when editing existing store
3. Open product from 1.
You will get the error `Uncaught Error: Call to a member function getSymbol() on null`

Prevent error when adding new store without currency

---

src/CoreShop/Bundle/OrderBundle/Resources/install/pimcore/classes/CoreShopOrder.json

Reports always filter on `orderDate` in https://github.com/coreshop/CoreShop/blob/2adc887c4fec31079a4e6ed896532b610526cbbc/src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php#L97
and
https://github.com/coreshop/CoreShop/blob/2adc887c4fec31079a4e6ed896532b610526cbbc/src/CoreShop/Bundle/CoreBundle/Report/CategoriesReport.php#L107-L108
Without an index on the `orderDate` field loading report data is really slow.
__Before this PR__
```mysql
explain SELECT SQL_CALC_FOUND_ROWS
`categories`.oo_id as categoryId,
`categories`.o_key as categoryKey,
`localizedCategories`.publicationsCategory as categoryName,
`orders`.store,
SUM(orderItems.totalGross) AS sales, …
```

[Reports] Add index for CoreShopOrder.orderDate to improve report performance

---

src/CoreShop/Bundle/IndexBundle/Messenger/Handler/IndexMessageHandler.php

This PR re-Implements the same behavior as in CS2. Without it, multi-level variants wont get updated:
https://github.com/coreshop/CoreShop/blob/100b1b3b90fbc876ce22610232b38549b5be5586/src/CoreShop/Bundle/IndexBundle/EventListener/IndexObjectListener.php#L85

[IndexBundle] check recursively child elements

---

src/CoreShop/Bundle/FrontendBundle/Controller/CustomerController.php
src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php
src/CoreShop/Component/Order/Repository/OrderRepositoryInterface.php

[FrontendBundle] fix only showing customer orders and not cars too

---

src/CoreShop/Bundle/CoreBundle/Resources/config/services/cart-processor.yml
src/CoreShop/Component/Core/Order/Processor/CartItemsProcessor.php
src/CoreShop/Component/Core/Order/Processor/CartSubtotalProcessor.php

This PR allows adding custom cart processors between `CartItemsProcessor` and cart subtotal calculation (`CartSubtotalProcessor`).
Otherwise, it is not possible to add custom adjustments **before** the subtotal **and** adjustments of the cart gets calculated.

Move Cart Subtotal Calculation To Dedicated Cart Processor

---

src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php
src/CoreShop/Bundle/OrderBundle/Resources/public/pimcore/js/order/editPayment.js

| Deprecation? | no
If your payment gateway provides nested details in given payments, the `order/detail` fetch will break (`Warning: Array to string conversion`)
This PR improves the detail grid view, if a detail value is not a simple array, it will be added as JSON encoded data to the grid (row body):

improve payment detail rendering

---

composer.json

Coreshop uses PHP8 language features and therefore should require it via `composer.json`.
This also has the nice benefit that at least in PHPStorm the language level is automatically pushed up to 8.0

Require at least php 8 via composer.json

---

src/CoreShop/Bundle/ResourceBundle/Resources/config/pimcore/admin.yml

| Fixed tickets | #2189 
Added event.js on ResourceBundle to avoid an undefined event if using the ResourceBundle standalone

fix: added event.js on ResourceBundle

---

src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php

Otherwise, all parent category ids will match with the containing same id (cat id = 1, matching ids; 1, 11, 111, 123)

restrict parentCategoryIds in filter index

---

src/CoreShop/Component/SEO/Extractor/TitleExtractor.php

MetaTitle can be null according to interface `CoreShop\Component\SEO\Model\SEOAwareInterface::getMetaTitle()` but `CoreShop\Component\SEO\Model\SEOMetadataInterface::setTitle()` always requires a string. This PR therefore adds a simple guard

Check first if metatitle is not null before setting it SEO TitleExtractor

---

src/CoreShop/Bundle/AddressBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/ConfigurationBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/CoreBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/CurrencyBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/CustomerBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/FixtureBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/FrontendBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/IndexBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/InventoryBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/LocaleBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/MenuBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/MoneyBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/NotificationBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/OrderBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/PaymentBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/PayumBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/PimcoreBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/ProductBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/ResourceBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/RuleBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/SEOBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/SequenceBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/ShippingBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/StoreBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/TaxationBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/ThemeBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/TrackingBundle/Resources/config/services_alias.yml
src/CoreShop/Bundle/WorkflowBundle/Resources/config/services_alias.yml

Starting with symfony/yaml:5.1, deprecations should contain both package and version and not just a message

Fix deprecation format

---

src/CoreShop/Component/Core/Provider/ContextBasedDefaultTaxAddressProvider.php

Assume we have a store with base country DE:
And we have tax rule 19% VAT for country Germany and 0% VAT for all other countries:
Initially without being logged-in the taxes shown on the website will be based on the store's base country. This is correct.
But when the client logs in, we already know his default address. In the checkout this gets used anyway but not when browsing through the site. On the site we still see taxes based on the store's base country. 
With this PR the logged-in customer's address will get used for displaying taxes also when browsing the shop.

Use shipping address of logged in customer for tax calculation

---

src/CoreShop/Component/Pimcore/Event/SlugGenerationEvent.php
src/CoreShop/Component/Pimcore/Slug/DataObjectSiteSlugGenerator.php

[Pimcore] add locale to SlugGenerationEvent

---

src/CoreShop/Bundle/StoreBundle/CoreExtension/Store.php

If show a `coreShopStore` (store select) field in grid you'll get no data
This is because `CoreShop\Bundle\StoreBundle\CoreExtension\Store` class hasn't method `getDataForGrid`
This method with all dependent methods `setOptions` and `getOptions` was copied from https://github.com/pimcore/pimcore/blob/10.5/models/DataObject/ClassDefinition/Data/Select.php (because Coreshop does not extend Pimcore's Select field type)
Only return data was changed from `return $data;` to `return $data?->getId();` because the getter returns a `Store` object via https://github.com/coreshop/CoreShop/blob/bb483e7279ac28af236caf8e8ff96001661cf70f/src/CoreShop/Bundle/ResourceBundle/CoreExte …

Support "store" field type in grid

---

src/CoreShop/Bundle/FrontendBundle/Resources/config/services.yml
src/CoreShop/Bundle/FrontendBundle/Twig/LocaleSwitcherExtension.php

Existing locale switcher doesn't change locale for static route pages such as /shop/login, /shop/cart, /shop/customer/profile etc. This happens because `$document` in https://github.com/coreshop/CoreShop/blob/738d977fea986e9ab13145c53b25ee00ed84f454/src/CoreShop/Bundle/FrontendBundle/Twig/LocaleSwitcherExtension.php#L50 relates to the document whose leftmost path matches the current URL. When you only have `/shop` as document but the remaining CoreShop pages are handled via static routes, even a request for `/shop/login` will have `$document = /shop`. Of course this document may have translations and so the wrong links get created.
This PR checks if a static route …

Adjusted locale switcher for internal shop pages without translations

---

src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php

Adjust ClassUpdate to allow $this->classDefinition to be assigned with null. Otherwise the assignment with the result of 
`DataObject\ClassDefinition::getByName($className)` may fail and the prepared null-check will not be reached.

Handle unknown class names in ClassUpdate
